### ISSUE TITLE
Tumble detection improvement

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie-firmware#1002]
The tumble detection is really good to avoid unnecessary damage to the Crazyflie when landing up-side down. However if a user don't know about this functionality it is confusing since the crazyflie needs to be restarted to fly again.

Suggestions:
- When tumble detection triggers show this with e.g. blinking the LEDs
- Print to cfclient console with useful information
- Make an automatic recovery when the crazyflie is turned back again

**Comment by whoenig** [comment]
I don't like the idea of an `automatic` recovery - that would be very dangerous if a user picks up the tumbled CF. Reset via a parameter (similar to resetting the EKF) would be nice, though.

**Comment by AsiaShi** [comment]
Thank you for your suggestions, I have increased the time to detect the tumble state, about 2s; Therefore, when I perform 360 ° flip operation, the UAV will not stop in an emergency, but when the tumbling time exceeds 2s, an emergency stop will be triggered. This is a better method I can think of at present. I look forward to your better improvement.

**Comment by knmcguire** [comment]
This issue might not be necessary anymore due to all the supervisor implementation lately.

https://github.com/bitcraze/crazyflie-firmware/pull/1272

**Comment by knmcguire** [comment]
So many things have changed here due to the supervisor implementation... so we will close this issue and consider it solved.
