### ISSUE TITLE
app wall following demo broken

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-firmware#1013]
I noticed that with Kbuild, and for some reason even release 2022.01, the wallfollowing app layer demo is broken. The last release that I checked where it worked, is 2021.06, so a lot could have happened in the mean time.

Now when I do:
`tb make_app examples/demos/app_wall_following_demo/`

, I get:
`make[4]: *** No rule to make target '/module/examples/demos/app_wall_following_demo/src/wall_following_multiranger_onboard.o', needed by '/module/examples/demos/app_wall_following_demo/src/built-in.o'.  Stop.`

**Comment by VladislavTempez** [comment]
There is a mismatch between the KBuild filenames and the actual filenames (missing _ in actual wall_following_multiranger_onboard names).

**Comment by knmcguire** [comment]
Ahhhh oke! I'll will try it out as soon as I have time. Thanks for the pointer @VladislavTempez !

**Comment by FelixBaum310** [comment]
@VladislavTempez 

> There is a mismatch between the KBuild filenames and the actual filenames (missing _ in actual wall_following_multiranger_onboard names).

Where exactly is the file where I have to changes these names?

**Comment by VladislavTempez** [comment]
crazyflie-firmware/examples/demos/app_wall_following_demo/src/

**Comment by FriendLiya** [comment]
Recently Come to meet the problem that...if I try to make and fly 2022.01 or 2022.03 bulids with crazyradioPA and android app,the phone app  "stop working and quit "immediately when pressing "connect "button.But only if go back to try 2021.06 version,everything is ok and fly smoothly.Just doute whether it gets the same cause.

**Comment by krichardsson** [comment]
@FriendLiya This comment does not seem to be related to the wall following app, please start a thread in the [forum](https://forum.bitcraze.io/) or create an issue in the relevant repository [bitcraze/crazyflie-android-client](https://github.com/bitcraze/crazyflie-android-client) instead
