### ISSUE TITLE
Position estimate can no longer be initialized to non-zero value

### ISSUE THREAD

**Issue by Kaiser1401** [bitcraze/crazyflie-firmware#1014]
It used to be possible to initialize / overwrite the drones estimated position by setting the parameters
```
kalman.initialX
kalman.initialY
kalman.initialZ
```
before setting 
`kalman.resetEstimation`
(see also describing [forum entry](url))

Commit d8d4878e4a1ebe79d7e1bbef24d81ec0c95589f9 unfortunatley 'destroyed' this behaviour.

In [estimator_kalman.c:437](https://github.com/bitcraze/crazyflie-firmware/blob/d8d4878e4a1ebe79d7e1bbef24d81ec0c95589f9/src/modules/src/estimator_kalman.c#L437) `kalmanCoreDefaultParams()` now ignores these values and uses zero instead:
https://github.com/bitcraze/crazyflie-firmware/blob/d8d4878e4a1ebe79d7e1bbef24d81ec0c95589f9/src/modules/src/estimator_kalman.c#L437
https://github.com/bitcraze/crazyflie-firmware/blob/d8d4878e4a1ebe79d7e1bbef24d81ec0c95589f9/src/modules/src/kalman_core/kalman_core.c#L125-L153

It would be nice to either restore the behaviour via the parameters or have another possibility to initialize a non-zero position

**Comment by krichardsson** [comment]
Yes, it looks like the original functionality has been broke and it should be restored.
Thanks for letting us know!
