### ISSUE TITLE
python binding functionality not properly intergrated into kbuild

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-firmware#1016]
The python bindings of the collision avoidance and trajectory planning has not been implemented into the kbuild properly, as it still builds within the bin/ file and does not get properly cleaned with make clean.

How to replicate:
```
make bindings_python
make clean
```
and observe the extra files that still exist after make clean

**Comment by whoenig** [comment]
We also get the following warning:

```
Makefile:215: warning: overriding recipe for target 'test_python'
tools/kbuild/Makefile.kbuild:147: warning: ignoring old recipe for target 'test_python'
```
