### ISSUE TITLE
Versioning of CPX protocol

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-firmware#1046]
Currently there's no version on the CPX protocol and this should be added. The suggestion is to take 2 of the MSB from the function field, which would then become 6 bits. Since with the current implementation the 2 MSB are already 0 we can decide that the first version of the protocol is 0 and the implementation will not be effected. It's just the definition of the package that will change.

This versioning is not something we need to enforce yet, we can wait until we have a next version.

**Comment by knmcguire** [comment]
Moreover, we should document the version as well
