### ISSUE TITLE
Watchdog suspicious reset on CF 1.0

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#105]
There has been some report of Crazyflie 1.0 reseting because of the watchdog.

It may be that the watchdog timing is a bit too tight for Crazyflie 1.0, this needs to be investigated.

**Comment by ottodog** [comment]
How can I help investigate?

**Comment by ataffanel** [comment]
Do you see the problem with the very last firmware from Master branch, ie. if you compile the firmware?

**Comment by ottodog** [comment]
The latest firmware works!

**Comment by ataffanel** [comment]
Thanks! We need to push a new firmware version then
