### ISSUE TITLE
CI does not use module.json

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-firmware#1051]
We have a module.json file that we used in the past but now has become kind of obsolete. Since we are planning to add more platforms to the firmware, it would be nice if the CI could take the platform from the files directly for a matrix actions. 

This should be possible with the function fromjson according to https://thekevinwang.com/2021/09/19/github-actions-dynamic-matrix/

**Comment by krichardsson** [comment]
Fixed in #1125
