### ISSUE TITLE
Implement additional functions when using eSky

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#12]
The eSky ET6i transmitter has not only two joysticks and a power on button, it also has three switches and two turning knobs. 

## Switches: ##
*  could be used to arm/disarm the quadcopter
*  Change mode: Easy (low max. pitch/roll/yaw) and Advanced (user defined max. pitch/roll/yaw)
*  Lock heading
*  Lock height
*  turn on Land mode (langing slowly to ground)

## Knobs: ##
*  Change max pitch&roll
*  Set max speed in %

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/12
- Originally Reported By: [Mathias ](http://bitbucket.org/Surrender)
- Originally Created At: 2013-07-03T12:08:29.220

**Comment by krichardsson** [comment]
Will not implement eSky support in CF2
