### ISSUE TITLE
binaries symlink can't be flashed

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-firmware#1243]
After the kbuild transfer, the binaries are created in the build/ which was first in the root folder. To solve that confusion, symlinks were created from those binaries to the main root of the folder:
https://github.com/bitcraze/crazyflie-firmware/blob/d9359ef2c700b685fe35ca69178c25c0c2625f36/Makefile#L126-L130

But if we do `make cload`, the script goes into the build folder and then flashes the 'original' binary file (WSL in windows)

```
make[1]: Entering directory '/home/knmcguire/development/bitcraze/c/crazyflie-firmware/build'
python.exe -m cfloader  flash  cf2.bin stm32-fw
```

If you try to do the cfloader from the root of the folder pointing to the symlink, this error occurs
```
-@-:~/development/bitcraze/c/crazyflie-firmware$ python.exe -m cfloader flash cf2.bin stm32-fw -w radio://0/65/2M/E7E7E7E7F2
Reset to bootloader mode ...
Failed to flash: [Errno 2] No such file or directory: 'cf2.bin'
```

The same thing happens with `make`  in the app layer examples to confuse even more.

So... apparently we never haven't used those symlinks and they just add confusion... should we just remove that line in the makefile?

**Comment by krichardsson** [comment]
They might be used by CI

**Comment by knmcguire** [comment]
So the idea of this one is, let's just remove these symlink generations and see what happens in the tests/CIs

Also we need to add in the documentation that the real binaries are in the build folder if they are not already
