### ISSUE TITLE
Attitude rate controller not working

### ISSUE THREAD

**Issue by jc-bao** [bitcraze/crazyflie-firmware#1258]
I use the attitude controller in `attitude_pid_controller.c` to control my crazyflie. 
I set the parameter in `crtp_commander_rpyt.c` as zero to use the attitude rate controller. 

```c++
static RPYType stabilizationModeRoll  = RATE; // Current stabilization type of roll (rate or angle)
static RPYType stabilizationModePitch = RATE; // Current stabilization type of pitch (rate or angle)
static RPYType stabilizationModeYaw   = RATE;  // Current stabilization type of yaw (rate or angle)
```

But the attitude rate behaves weirdly. I set a certain roll rate setpoint through crazyswarm2. But the attitude seems to rise slightly, then fall back to zero. 

<img width="200" alt="image" src="https://user-images.githubusercontent.com/60093981/227706780-bba2c5f4-d65a-4412-a4d7-323d00399798.png">

The dashed blue line is my setpoint, while the orange line is the actual drone attitude rate calculated from the attitude. 

I'd like to know why the roll rate thrust quickly and fell back to zero. I have converted the command to the [degree measurement ](https://github.com/jc-bao/crazyswarm2-adaptive/blob/e9fc90ab87d88f41f9c5d577d82d2e64da6644af/src/crazyswarm2/crazyflie_examples/crazyflie_examples/attitude_ctl.py#L204) and tried different [PID control parameters](https://github.com/jc-bao/crazyswarm2-adaptive/blob/e9fc90ab87d88f41f9c5d577d82d2e64da6644af/src/crazyswarm2/crazyflie/config/crazyflies.yaml#L18). But things seem not to work out. 
I would greatly appreciate any comments. Thanks!

**Comment by jc-bao** [comment]
I believe the issue has been resolved. I attempted various controllers and utilized cflib to directly call the attitude rate controller. This led me to discover that the issue was located within my crazyswarm2 settings, specifically regarding the controller type and Kalman filter parameters.

Once I updated the launch file parameters, I was able to achieve a notably improved attitude rate control performance.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/60093981/227771801-2fc57db8-d751-4895-a34d-905f9a917478.png">

**Comment by gy2256** [comment]
Hi, whhich flight mode do you choose to enable the attitude rate control?

**Comment by knmcguire** [comment]
Could you start a new discussion thread? since you already closed this one

**Comment by knmcguire** [comment]
I mean, to start a discussion thread here: https://discussions.bitcraze.io/. We'd like to not have questions in the issue thread unless it constitute something that needs to be fixed.

**Comment by gy2256** [comment]
Ok. Thanks!
