### ISSUE TITLE
Memory handler registration broken in current master

### ISSUE THREAD

**Issue by ntamas** [bitcraze/crazyflie-firmware#1260]
[This line](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/mem.c#L67) resets the number of memory handlers registered in the firmware to zero when `memInit()` is called. Unfortunately, with the current boot sequence, it is possible to register memory handlers _before_ `memInit()`; in particular, the EEPROM memory and the trajectory memory are registered earlier. Example calling sequence: `systemInit() --> configblockInit() --> eepromInit() --> memoryRegisterHandler()` registers the EEPROM memory, but the registration is cleared later when `systemTask()` calls `memInit()`.

I think that `memInit()` should probably be moved to `systemInit()` but I'm not sure if this is the best course of action.

_Edit_: fixed link

**Comment by krichardsson** [comment]
Thanks for pointing this out!

One could generally argue that it is bad that the `memoryRegisterHandler()` function is called before the module is initialized, but let's leave it like this for now. The original change was a refactoring to separate CRTP from the memory sub system.

The init sequence needs a bit of love for sure, it's on the radar, but will be done at some other point.
