### ISSUE TITLE
Tutorial for Collision Avoidance

### ISSUE THREAD

**Issue by devbf** [bitcraze/crazyflie-firmware#1280]
Hello,

We are a small team of students using crazyflies for a small project. At the moment we are using Crazyswarm to use collision avoidance for multiple drones. In our case we have a small swarm of 4 drones which should be able to avoid a collision if another drone flies into the same swarm (while all drones are into the same channel).

We noticed that one of the developers, @jpreiss, has also implemented collision avoidance in the native crazyflie-firmware (https://github.com/bitcraze/crazyflie-firmware/pull/628). But at the moment we are not really sure how we can utilize this function. Using the crazyflie-firmware with cflib commands, we already had some crashes, so it seems that the collision avoidance between two drones is not enabled by default.

Is there any way to use the collision avoidance in the crazyflie-firmware in a way like you can with Crazyswarm using the [enableCollisionAvoidance](https://crazyswarm.readthedocs.io/en/latest/api.html#pycrazyswarm.crazyflie.Crazyflie.enableCollisionAvoidance) function using the cflib?

As the student project currently only uses python programs in combination with cflib and is not really fond of the thought of using Crazyswarm in addition to the existing programs, we would be really glad if someone has a hint on how to use collision avoidance for normal drone flights using the cflib.

Thanks for your answers and sorry if I have made any mistakes, this is my first issue on GitHub :)

Flo

**Comment by krichardsson** [comment]
See https://github.com/orgs/bitcraze/discussions/733
