### ISSUE TITLE
Partly missing messages in CPX logging

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#1304]
A user had problems with console log messages from the GAP8 that were tuncated, [see discussion](https://github.com/orgs/bitcraze/discussions/822). It seems as it is related to the messages not being terminated with "\n" and even though the problem was solved I think there are some things that need to be investigated.
1. It looks like the log message sent from the GAP8 actually is terminated with a "\n" but still another one needed to be in the STM to make it work. Was the original one lost?
2. Why is the first part of the message lost? I would expect the full message to be written to the console log buffers, but that it is not sent to the client until later, if a "\n" is missing.

**Comment by evoggy** [comment]
Cannot be reproduced so I'm closing this. But if anyone can supply some code (on GAP8 and STM32 side) to reproduce it please re-open the issue and attach it.
