### ISSUE TITLE
ACtivating or deactivating FPU 

### ISSUE THREAD

**Issue by sAz-G** [bitcraze/crazyflie-firmware#1353]
I would like to make sure that the FPU  is activated, I guess [this code](https://github.com/bitcraze/crazyflie-firmware/blob/f61da11d54b6d54c7fa746688e8e9be4edd73a29/Makefile#L28) is needed during the compilation in order to activate the FPU, but is it necessary to activate the FPU also during run time?

In case the FPU is activated by default, is it straightforward to deactivate the FPU?

**Comment by ataffanel** [comment]
This line is indeed activated the FPU support in GCC. If you remove ```-mfloat-abi=hard -mfpu=fpv4-sp-d16```, it will get gcc to use a software implementation of floating point operation (it is possible, while rare, to get a Cortex-M4 without FPU so this is why this option exists in GCC).
