### ISSUE TITLE
mm.flow parameter

### ISSUE THREAD

**Issue by AsiaShi** [bitcraze/crazyflie-firmware#1367]
I just want to know what is the meaning of parameter ‘thetapix’ ，Can you elaborate on that?

**Comment by gemenerik** [comment]
Check out [this discussion](https://github.com/orgs/bitcraze/discussions/376) and the fix in #1189. See [this comment](https://github.com/hmllr/crazyflie-firmware/blob/master/src/modules/src/kalman_core/mm_flow.c#L45) in the code.
