### ISSUE TITLE
Whether the rateDesired.roll, rateDesired.pitch, rateDesired.yaw needs to be converted to the body coordinate system before executing the attitudeControllerCorrectRatePID(sensors->gyro.x, -sensors->gyro.y, sensors->gyro.z, rateDesired.roll, rateDesired.pitch, rateDesired.yaw); ?

### ISSUE THREAD

**Issue by HelloIDTC** [bitcraze/crazyflie-firmware#1368]
Whether the rateDesired.roll, rateDesired.pitch, rateDesired.yaw needs to be converted to the body coordinate system before executing the attitudeControllerCorrectRatePID(sensors->gyro.x, -sensors->gyro.y, sensors->gyro.z, rateDesired.roll, rateDesired.pitch, rateDesired.yaw); ?
Because the sensors->gyro.x, gyro.y, gyro.z is measured in the body coordinate system, roll, pitch, yaw euler's angular (rate) is in Earth coordinates.

**Comment by knmcguire** [comment]
Duplicate of https://github.com/orgs/bitcraze/discussions/1303 so closing.
