### ISSUE TITLE
Bolt: one motor doesn't spin

### ISSUE THREAD

**Issue by AdrienGuenard** [bitcraze/crazyflie-firmware#1389]
Hello,
I am facing a bug with recent version of firmware built for bolt config: 1 of the 4 motors doesn't spin. Has anyone else noticed the problem? I think that this problem may come from commit 3d5129ff6afbde9bfe12cc70cb0dfaf948423316

**Comment by tobbeanton** [comment]
I can confirm the [problem](https://github.com/bitcraze/crazyflie-firmware/commit/3d5129ff6afbde9bfe12cc70cb0dfaf948423316#diff-f0379ea184fe2cefaa1e47311527c3a7f32d1b863f9c0a3ff682fe6110e74b96R246), it is the Crazyflie brushless ESC reset pin that conflicts with the Bolt M4 mosfet. We will try to have a fix soon.

**Comment by tobbeanton** [comment]
A fix #1391 has now been submitted. Please try with that.

**Comment by AdrienGuenard** [comment]
Thank you, it seems solved!
