### ISSUE TITLE
Incorrect dt passed to sensfusion6UpdateQ

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#14]
I have added some debug logging to my local mod of Crazyflie firmware and realized that sensfusion6UpdateQ gets a predefined dt=0.004 s (4 ms), but the actual delays between these calls are 8-10 ms.

I have a fix for that: https://bitbucket.org/krasin/crazyflie-firmware/commits/218bf25b6e28b42705636dd8bb0bcac0053c0c53

After the fix, Crazyflie is a bit more stable, which is not surprising, because the internal model now gets the right value of g constant (before that, the copter virtually had a higher gravitation). 

If it looks fine, I will create a pull request (right now, I am failing to do that, because I have not figured out how to create a separate branch in Mercurial, and I already have a pull request in default branch: https://bitbucket.org/bitcraze/crazyflie-firmware/pull-request/9/fix-url-to-open-x-imu-algorithm/diff).

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/14
- Originally Reported By: [ ](http://bitbucket.org/krasin)
- Originally Created At: 2013-07-26T05:15:13.021

**Comment by krichardsson** [comment]
We are looking at new control algorithms and will rewrite this code. Closing

**Comment by ataffanel** [comment]
Closing for real :-).
