### ISSUE TITLE
Crazyflie takes a very long time to lock IMU

### ISSUE THREAD

**Issue by theseankelly** [bitcraze/crazyflie-firmware#141]
Sometimes, it takes a very very long time (over a minute) before my crazyflie finishes the IMU init (and the red led starts pulsing faster).

I think, but am not certain, this has to do with when I'm trying to take off from unlevel surfaces like the ground, or a pile of papers on my desk.

**Comment by tobbeanton** [comment]
This is something that came with improved bias calibration, and I agree, now it is way to conservative. It is the [GYRO_VARIANCE_BASE](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/hal/src/imu_cf2.c#L78) constant that needs to be increased to relax the calibration threshold.
