### ISSUE TITLE
Bugs: A serious calculation error was discovered in the lighthouse positioning system

### ISSUE THREAD

**Issue by madzhen** [bitcraze/crazyflie-firmware#1421]
I don't think this question is important right now, I will close it

**Comment by madzhen** [comment]
![center4](https://github.com/user-attachments/assets/3be6890b-7f22-4f90-83fd-18ad63ff7a12)
![center3](https://github.com/user-attachments/assets/15e66e14-b475-4b51-b253-1c61b59a006a)
This paper also gives the same formular

**Comment by ataffanel** [comment]
Hi,

We have not observed huge positioning errors in Lighthouse V1 and this code has been there and used for a while already. Have you observed problems when using Crazyflie with basestation-V1?

This problem will not propagate to lighthouse-V2 since the two systems have completely different frame times, lighthouse V2 using different rotation speed per channels.

**Comment by madzhen** [comment]
> Hi,
> 
> We have not observed huge positioning errors in Lighthouse V1 and this code has been there and used for a while already. Have you observed problems when using Crazyflie with basestation-V1?
> 
> This problem will not propagate to lighthouse-V2 since the two systems have completely different frame times, lighthouse V2 using different rotation speed per channels.


This error does not cause a huge positioning error. This error will cause a deviation between the base station posture identified by the localization method and the actual posture of the base station. For example, if the base station is placed horizontally, if this error exists, it will be identified as tilted.

The new problem I raised will cause deviations:
[https://github.com/bitcraze/crazyflie-firmware/issues/1423](https://github.com/bitcraze/crazyflie-firmware/issues/1423)

That problem will cause the deviation to be greater the farther the positioning board is from the base station. Crazyfile does have this problem at present, and the positioning error at a distance will be about 1cm. I hope you can check whether it is a symbol error.

I also checked the project you referenced, Nasa's astrobee, and your phase correction was transplanted from nana's astrobee project. I carefully derived the mathematical formulas in it and checked the astrobee code. I am sure there is a symbol inconsistency here. The following figure shows the inconsistency between the astrobee code and the crazyfile code:

the following figure is your version：
![gibphase problem](https://github.com/user-attachments/assets/36c0b028-2b7c-4159-ae70-77376276411c)

the following figure is nasa astrobee version：
![gibphase problem2](https://github.com/user-attachments/assets/bff813ae-f593-4251-87d7-f8c88904fa36)

compare the compGib term, astrobee version is different from yours.
