### ISSUE TITLE
Error Cloning CMSIS Submodule

### ISSUE THREAD

**Issue by cookacola** [bitcraze/crazyflie-firmware#1434]
I'm currently using MacOS with the toolbelt. After cloning recursively, it seems like there are issues cloning the correct submodules, especially CMSIS.

**Comment by cookacola** [comment]
Specifically, 
Unable to checkout 'a65b7c9a3e6502127fdb80eb288d8cbdf251a6f4' in submodule path 'vendor/CMSIS'

**Comment by cookacola** [comment]
fatal: the remote end hung up unexpectedly
fatal: Unable to checkout 'a65b7c9a3e6502127fdb80eb288d8cbdf251a6f4' in submodule path 'vendor/CMSIS'

Still this error persists.

**Comment by ataffanel** [comment]
I cannot reproduce the error on my side. Can you try to clone using ssh instead, this way you might get more quota from GitHub to download cmsis:
```
git clone git@github.com:bitcraze/crazyflie-firmware --recursive
```

**Comment by cookacola** [comment]
Now that works. It seems that it's an issue only to HTTPS. Thank you.

**Comment by cookacola** [comment]
SSH Works

**Comment by cookacola** [comment]
Still receiving this error even with SSH

git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
fatal: Unable to checkout 'a65b7c9a3e6502127fdb80eb288d8cbdf251a6f4' in submodule path 'vendor/CMSIS'

**Comment by cookacola** [comment]
However, it seems that if I do install git-lfs, it should work.
