### ISSUE TITLE
Yaw absolute mode

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#15]
Currently the Yaw is controlled in rate mode. There should be a parameter allowing to switch to absolute mode (with 0 degree being the take-off position).

One use case is to allow for controlling the yaw from an android phone orientation.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/15
- Originally Reported By: [Arnaud Taffanel](http://bitbucket.org/ataffanel)
- Originally Created At: 2013-07-30T06:49:43.409

**Comment by ataffanel** [comment]
This is implemented in current firmware
