### ISSUE TITLE
EKF initial location problem when the Crazyflie is started outside the anchor convex hull

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#155]
It has been reported that the EFK initial location cannot be found if the Crazyflie is started outside the anchor system convex hull. This still has to be confirmed.

**Comment by knmcguire** [comment]
Tested this out with the latest release 2020.06 with TWR, TDOA2 and 3. This problem seems to have solved itself! Probably to be expected with 4 years of LPS improvements (still a lot to do but at least this is not one of them anymore).

Closed!
