### ISSUE TITLE
dt should be passed to the pidUpdate function

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#16]
The delta time in the pidUpdate function is hard coded and wrong. This should be fixed and it will affect the I-term gain which could be a problem for people that has tuned their PID them selves.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/16
- Originally Reported By: [Tobias Antonsson](http://bitbucket.org/tobbeanton)
- Originally Created At: 2013-07-31T16:12:28.686

**Comment by krichardsson** [comment]
We are looking at new control algorithms and will rewrite this code. Closing
