### ISSUE TITLE
Use timeout based on radio activity for PM shutdown

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#17]
The timeout for shutting down the Crazyflie down due to inactivity is based on when the last commander packet was received, not when the last radio activity occurred. So if someone would use the Crazyflie only for logging (and not send any commander packets) the Crazyflie would shut down when this timeout is reached.

The timeout should instead be based on the last radio activity.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/17
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-09-19T14:41:51.938

**Comment by ataffanel** [comment]
Since the Crazyflie has now much more autonomous capabilities, it does not make sense to have the motor shut down on radio, shut down needs to be handled differently for different flight mode.
