### ISSUE TITLE
Integrate the v53l0x ranging with the EKF

### ISSUE THREAD

**Issue by mgreiff** [bitcraze/crazyflie-firmware#173]
Presently, the v53l0x laser sensor deck provides measurements ~0.1-1.3 [m] with a precision measured in [mm] depending on the surface albedo. An implementation should be made to include these measurements in the EKF by queuing  and entering data by means of scalar updates.

**Comment by stephanbro** [comment]
I would suggest to add an easy way to disable the ranging updating the EKF, as I've been using the sensor as a scanner.

**Comment by mgreiff** [comment]
Good point. I just submitted a pull request with a functional implementation, but I'll revise it so that measurements are not pushed into the Kalman by default when using the ranging+EKF.
