### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vpaesmans** [bitcraze/crazyflie-firmware#179]
Hi.

I get the following error 
src/hal/src/freeRTOSdebug.c: In function 'vApplicationMallocFailedHook':
src/hal/src/freeRTOSdebug.c:46:4: error: implicit declaration of function 'uartPrintf' [-Werror=implicit-function-declaration]
    DEBUG_PRINT("\nMalloc failed!\n");
    ^
cc1: all warnings being treated as errors
tools/make/targets.mk:26 : la recette pour la cible « freeRTOSdebug.o » a échouée
make: *** [freeRTOSdebug.o] Erreur 1

while compiling with CFLAGS += -DDEBUG_PRINT_ON_UART

Hope it helps.
Vincent.

**Comment by krichardsson** [comment]
Hmm, yes, looks as no one really touched this code for a couple of years and that it has decayed. I fixed the compilation issues but have not really tested that we get any data on the UARTs.
