### ISSUE TITLE
eskylinkDecode function wrong?

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#19]
static CRTPPacket crtpPacket;
  float pitch, roll, yaw;
  uint16_t thrust;
  
  pitch = ((packet[2]<<8) | packet[3])-PPM_ZERO;
  if (**roll**<(-PPM_RANGE)) **roll** = -PPM_RANGE;
  if (**roll**>PPM_RANGE) **roll** = PPM_RANGE;
  pitch *= 20.0/PPM_RANGE;

should this be

  pitch = ((packet[2]<<8) | packet[3])-PPM_ZERO;
  if (**pitch** <(-PPM_RANGE)) **pitch** = -PPM_RANGE;
  if (**pitch** >PPM_RANGE) **pitch** = PPM_RANGE;
  pitch *= 20.0/PPM_RANGE;
  
 

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/19
- Originally Reported By: [vision dual](http://bitbucket.org/wwfiney)
- Originally Created At: 2013-12-08T03:44:29.944

**Comment by tong** [comment]
Still exists in 2017.06 release
