### ISSUE TITLE
Crazyflie can be wrongly calibrated if moved intensly during calibration phase.

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#2]
After the Crazyflie is powered on it will start a gyro calibration function. This functions waits for the Crazyflie to become stable/still and then takes the gyro bias. It seems however that if you move the Crazyflie intensely during this phase it can falsely detect that it is stable/still and take a wrong bias.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/2
- Originally Reported By: [Tobias Antonsson](http://bitbucket.org/tobbeanton)
- Originally Created At: 2013-05-03T11:58:18.671

**Comment by krichardsson** [comment]
Can not reproduce
