### ISSUE TITLE
Bad argument vTaskSetApplicationTaskTag(0, (void*)TASK_PM_ID_NBR); ?

### ISSUE THREAD

**Issue by x893** [bitcraze/crazyflie-firmware#21]
pm.c
vTaskSetApplicationTaskTag(0, (void*)TASK_PM_ID_NBR);
but in tasks.c
void vTaskSetApplicationTaskTag( xTaskHandle xTask, pdTASK_HOOK_CODE pxHookFunction )

Correct ?

**Comment by tobbeanton** [comment]
From what I see it is implemented correctly. By setting the xTaskHandle to 0 it will take the current running task.
