### ISSUE TITLE
Mixed line endings appearing in new commits.

### ISSUE THREAD

**Issue by JGSuw** [bitcraze/crazyflie-firmware#216]
I'm seeing carriage returns showing up in places where they don't belong in recent commits, which will certainly lead to spurious diffs in future pull requests. Perhaps a repository [.gitattributes](https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings) file can be used to correct this issue in the future. Also, it may be worth adding a small section to the readme informing Windows contributors of the CRLF vs LF issue, as they may want to config their git to checkout as-is and commit unix-style in the future. At least they should just be aware of the issue.

**Comment by ataffanel** [comment]
Hi, this sounds like a good idea. So do I understand well that if we add a .gitattribute file git will transparently handle the conversion during commit?

For windows people, I think the line ending setting is a question during installation, so it might not be necessary to repeat it in our readme.
