### ISSUE TITLE
Add E-Stop support and packet

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#226]
When flying autonomous flight it is very important to be able to stop the Crazyflies quickly, so essentially we need an Emergency Stop. Currently this is implemented by software sending setpoint to the crazyflie, for example the ROS driver is sending a setpoint that stops the motors and then disconnect.

For a future demo we are going to run the Crazyflie fully autonomous (ie. with internal hardcoded setpoint sequence), and so we need a real E-Stop that is not related to the currently sent setpoint.

This is a proposal on how E-Stop can be implemented:
 - A state is added to stabilizer.c to record if E-Stop has been activated or not, if an E-Stop condition is activated a power of 0 is sent to the power distribution. This means that the E-Stop is independant of any controller or other algorithms in the stabilization loop.
 - 2 boolean are added to the setpoint structure: setEStop and resetEStop. This means that the E-Stop is bistable and needs to be actively reset if it has been set.
 - A new commander packet is added to set and reset the E-Stop condition. This packet can be sent as unicast or broadcast packet.
 - Two new function stabilizerSetEStop() and stabilizerResetEstop() allows to set the E-Stop condition from within the Crazyflie.

Optional: 
 - Set the LEDs to a special state when E-Stop is set to indicate to the user why the Crazyflie is not flying

Any comment, something I am forgetting or that can be done more useful or better?

**Comment by krichardsson** [comment]
It would be nice to have a "run away" safe mode. 
I'm thinking that the emergency stop system continuously sends reset packets. If no reset packet is received in the Crazyflie within some period it enters emergency stop state and falls down.

The scenario could for instance be when flying autonomously and the coper is out of reach of the emergency system radio (maybe a run away copter outside), or the emergency system breaks down for some reason.
