### ISSUE TITLE
flashing issue

### ISSUE THREAD

**Issue by jlamyi** [bitcraze/crazyflie-firmware#24]
Hi! When I try to flash or launch openocd, it gives me an error of "cannot find the ftdi device". I tried to change the configure file or the rule, but it does not help. Do you know what may be a reason to cause this issue? Thanks

**Comment by tobbeanton** [comment]
This is not a crazyflie-firmware related issue but related to openocd and the JTAG/SWD debugger used so I'm closing it. Please use the [forum](http://forum.bitcraze.se/) instead.
