### ISSUE TITLE
Implement full pose measurement in EKF

### ISSUE THREAD

**Issue by jpreiss** [bitcraze/crazyflie-firmware#246]
The current EKF implementation supports a position measurement à la GPS, but no full pose measurement. In a motion capture system the orientation measurement is also available. Including this information can only improve the state estimation.

I am happy to do the needed work on the radio protocol and the ROS driver, but it would be nice to get some support from an `estimator_kalman.c` author for the EKF changes.

**Comment by ataffanel** [comment]
As far as I understand the full pose input implementation in the current EKF is not obvious. Though, I think this kind of interface should be (as far as possible) independent of any particular algorithm anyway so feel free to propose an interface.
