### ISSUE TITLE
Freefall detection with Flow deck

### ISSUE THREAD

**Issue by fredg02** [bitcraze/crazyflie-firmware#259]
Freefall detection with Flow deck should activate position hold (at default height, e.g. 40cms) and landing sequence after a little delay (e.g. 5 sec).

**Comment by krichardsson** [comment]
It might work, assuming it is free falling with the correct orientation in the air so that the laser ranger can measure the distance to the ground. There is also a risk that the Kalman filter has not converged and we don't understand where we are. It is worth a try though.

**Comment by knmcguire** [comment]
Its a nice idea, but I personally think that the Flowdeck is not suitable for this and this should probably be done with the IMU instead or an external positioning system. There is already a sitAw module that detect this so this could be a really cool application. However I don't think this should be actual part of the firmware but separate as with the app-layer. 

As this is an old issue with low activity I will close it for now !
