### ISSUE TITLE
Buzzer deck is "buzzing" constantly

### ISSUE THREAD

**Issue by fredg02** [bitcraze/crazyflie-firmware#261]
I noticed that my Buzzer deck is "buzzing" constantly, not very loud, but audible. It sounds similar to the noise of a coil and can be heard best, when the CF with the buzzer deck is put close to an ear.
It's buzzing when the CF is on, even when it's not connected to a client.

**Comment by krichardsson** [comment]
On mine too

**Comment by ataffanel** [comment]
I tested with the latest firmware and I cannot hear anything and there is no voltage variation around the buzzer: just a constant 3V. So it must have been fixed already. Do not hesitate to re-open the issue if not.
