### ISSUE TITLE
store fly data

### ISSUE THREAD

**Issue by gianand** [bitcraze/crazyflie-firmware#279]
Hi all, I'm a beginner of phyton programming and I'd like to know how to modify the file basiclog.py so that it can store flight data in a .txt file. Thank you

**Comment by krichardsson** [comment]
Hi!

This is a good questions, but please ask it on the forum instead (https://forum.bitcraze.io/) since this is related to how to use the system. We are trying to use issues for development discussions such as bugs and feature requests.

Thanks!

- Kristoffer
