### ISSUE TITLE
PID Tuning

### ISSUE THREAD

**Issue by RCYajad** [bitcraze/crazyflie-firmware#282]
Hi! We've recently bought a expansion deck for our crazyflie to make it into a bigger quad. I've read in the wiki that we need to vary the values here.

![image](https://user-images.githubusercontent.com/18350570/34916813-f3cd982c-f978-11e7-9222-793cac83bbd5.png)

My questions are the following:

1.) Is there any recommended setup so that we can tune the PID without damaging the quad?
2.) Whats the purpose of the RATE values (PID_ROLL_RATE_KP, PID_ROLL_RATE_KI, etc etc.)  and do we need to modify them?
3.) And, the best way to tune the pid?

**Comment by tobbeanton** [comment]
We would prefer moving this to the support part of the Crazyflie [forum](https://forum.bitcraze.io/viewforum.php?f=5). Could you please post there instead? [Here](https://forum.bitcraze.io/viewtopic.php?f=6&t=1978&hilit=tuning) is a PID tuning discussion in the forum.
