### ISSUE TITLE
Add sanity check of setpoint values before motors start.

### ISSUE THREAD

**Issue by mlundh** [bitcraze/crazyflie-firmware#30]
The CF2 firmware should do some sanity checking before allowing to start the motors. If, for example, the PS3 controller is not started but only inserted, the thrust value might be stuck at 100%. If one then connect to the CF2 it will start immediately with thrust at 100%, resulting in a violent crash. It would be preferable to have an arming procedure, for example requiring 0% throttle and neutral stick input before the firmware allows the motors to start.

**Comment by ataffanel** [comment]
Implemented a check for thust=0 before unlocking the thrust commands. This is enough to fix the bug related to game-pads locked to 100% thrust.
