### ISSUE TITLE
Is LPS implemented with Sensor Fusion?

### ISSUE THREAD

**Issue by NicksonYap** [bitcraze/crazyflie-firmware#316]
Hi,

I am aware Ardupilot uses DW1000 combined with Sensor Fusion.
(DW1000+Accel, Gyro, compass data for 3D positioning)

Does Crazyflie 2.0 use DW1000 with Sensor fusion?

Best

**Comment by krichardsson** [comment]
Yes, we use a kalman filter to fuse data from available sensors.

Also, please ask this type of questions in the https://forum.bitcraze.io/ instead, we try to use issues on github for bugs and features.
