### ISSUE TITLE
Add "not implemented" reply for ports that are not handled

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-firmware#32]
If a message is sent to a port that's not handled the firmware will just quietly discard the packet. Instead a "not implemented" packet should be sent back to indicate that the message was received, but the functionality is not available. This will make it easier to implement new ports on new platforms without causing backwards compatibility issues with clients.

**Comment by ataffanel** [comment]
We added a way to request the protocol version which should be enough to discover if a functionality exists or not.
