### ISSUE TITLE
Pushing dangling pointer to the kalman queue

### ISSUE THREAD

**Issue by sdalu** [bitcraze/crazyflie-firmware#323]
Reading the following code, it looks like a pointer to a local variable is pushed to the queue 😱 

https://github.com/bitcraze/crazyflie-firmware/blob/18104df81913d7f9359c4d5768123292864e24b2/src/deck/drivers/src/lpsTwrTag.c#L198-L207

**Comment by krichardsson** [comment]
When data is added to the queue it is coped, so it is not a problem. For more information take a look at https://www.freertos.org/a00117.html

Thanks for the heads up!
