### ISSUE TITLE
Controller mellinger yaw direction reversed

### ISSUE THREAD

**Issue by kyuhyong** [bitcraze/crazyflie-firmware#335]
I tried to compare using PID and Mellinger for controller and found their yaw direction is opposite. 
In cfclient, right yaw commands gives positive deg/s while left yaw gives negative deg/s
with PID controller, cf2 turns right when I commanded right yaw however
with Mellinger controller, cf2 turns left for the same command.
Is this intentional? 
I tried to modify some code in the mellinger.c but changing the input does not help solving this issue. 
Thanks,

Kyu

**Comment by krichardsson** [comment]
I think I'll pass this one on to @whoenig
Thanks!

**Comment by whoenig** [comment]
This is not intentional and sounds like a bug to me. The mellinger controller was more heavily tested for operation in a mocap, so this might be related to the slightly separate manual flight mode. I'll take a look.

**Comment by kyuhyong** [comment]
I applied the fix and tested with my drone today. 
It seems the issue is gone with both CONTROLLER: Using controller 2 or 1
Thanks,
Kyu
