### ISSUE TITLE
Use of digitalRead on STM Pin instead of Deck Pin

### ISSUE THREAD

**Issue by sdalu** [bitcraze/crazyflie-firmware#336]
IRQ check loop in locodeck is only done once
https://github.com/bitcraze/crazyflie-firmware/blob/0205a85b81cd9806caf6c41d19f8f4940c33a859/src/deck/drivers/src/locodeck.c#L280-L282

due to use of digitalRead
https://github.com/bitcraze/crazyflie-firmware/blob/0205a85b81cd9806caf6c41d19f8f4940c33a859/src/deck/api/deck_digital.c#L61-L65

**Comment by ataffanel** [comment]
Thanks for catching that! We should use the stm32 periph lib GPIO api instead of the deck API there.

**Comment by krichardsson** [comment]
Fixed in #368
