### ISSUE TITLE
Implement headfree mode

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-firmware#36]
Using headfree mode front is always in the same direction (on the yaw), even if the Crazyflie is rotating. This makes it a lot easier for new users to fly around. This functionality should be controlled using a parameter so hosts can easily switch it on/off.

**Comment by capriele** [comment]
Hi, i've implemented this mode into my custom firmware. 
This is the link (see stabilizer.c)
https://github.com/capriele/crazyflie-firmware

**Comment by evoggy** [comment]
Great work, thanks! Could you create a pull-request for us and we will merge it in.

**Comment by krichardsson** [comment]
Implemented in 7cc43495522b55036631c8bc66b0033375f83816
