### ISSUE TITLE
SYS: Assert failed at src/modules/src/estimator_kalman.c:857

### ISSUE THREAD

**Issue by benkuper** [bitcraze/crazyflie-firmware#369]
On latest git version as of this writing

**Comment by krichardsson** [comment]
Rev 3d73ba300681d980b7a14373e51cac2ab8ec912e

**Comment by krichardsson** [comment]
@benkuper Which mode were you using?

**Comment by benkuper** [comment]
TDoA V2

**Comment by krichardsson** [comment]
Related to #320. There are a number of asserts that seems to be triggered from time to time, mainly in TDoA. Let's handle all these issues in #320. Closing
