### ISSUE TITLE
Add support for multiple hardware platforms

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#379]
The new hardware platform CF2.1 is released in the near future. Some modifications of the firmware will be necessary since the CF2.1 has different sensors. It is also plausible that there will be other platforms in the future.
The implementation should:
* be able to identify the underlying hardware platform
* initialize the correct drivers based on the platform
* detect unsupported platforms and fail fast to avoid possible damage

**Comment by NicksonYap** [comment]
@krichardsson 
We've gotten our hands on 7 crazyflies, 9 anchors, HTC Vive, & Kinect (and more sensors coming)
Can my company (http://seamlesshq.com) get early access to Lighthouse deck & CF2.1?

Would be happy to test em out :)

I'm thinking of using the Lighthouse deck as ground truth for the Loco deck.
It could possibly be used to optimise/tune the Loco deck calibrations
