### ISSUE TITLE
CPPM on BigQad deck interferes with SPI deck bus

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie-firmware#383]
Since the CPPM input on PA7 interfere with the deck SPI-MISO, it can't be used with decks that use the SPI bus. Make the CPPM functionality configurable.

**Comment by jonasdn** [comment]
Is this problem still an issue? What should be done?

**Comment by matejkarasek** [comment]
I will soon create a PR, just some cleanup needed:
[https://github.com/flapper-drones/crazyflie-firmware/tree/improved_CPPM_altGPIO](url)

**Comment by knmcguire** [comment]
I believe this has been already merged in the code base with an PR right? I'll close it now but please reopen if I'm wrong
