### ISSUE TITLE
flow deck algorithm

### ISSUE THREAD

**Issue by mandelyoni** [bitcraze/crazyflie-firmware#385]
Hi ,

Is the code for the optical flow open source?

Thanks,  Yoi

**Comment by krichardsson** [comment]
Yes, mainly implemented in
https://github.com/bitcraze/crazyflie-firmware/blob/master/src/deck/drivers/src/flowdeck_v1v2.c
https://github.com/bitcraze/crazyflie-firmware/blob/master/src/drivers/src/pmw3901.c
https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/estimator_kalman.c

**Comment by NataliaOgor** [comment]
Hi,

where's the flowdeck initialized? Trying to find the usage of flowdeck2init

Thank you,
Natalia

**Comment by mandelyoni** [comment]
Hi,

Try looking above at krichardsson's answer

**Comment by NataliaOgor** [comment]
Hey, thanks,
I did, in flowdeckv1v2 the task and init functions are declared, kalmans estimator processes measurements for flow and tof and pwm3901 works with motion.
But i haven't found where the flowdeck is initialized. I suppose it's done in deck.c within a loop in the deckInit() function, but i cannot find the mapping from a deck to it's driver then.

**Comment by krichardsson** [comment]
Hi @NataliaOgor! 

To outline the deck init process:
1. Installed decks are enumerated and identified through their One Wire memories
1. Decks that were forced at compile time are added to the list
1. The drivers are initialized

The calls to the deck init functions are done from https://github.com/bitcraze/crazyflie-firmware/blob/master/src/deck/core/deck.c#L64.
