### ISSUE TITLE
Fail to connect via USB and get logs multiple times

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#394]
From issue bitcraze/crazyflie-lib-python#109

How to reproduce:

1. Start a Roadrunner or Crazyflie
1. Connect via USB to a computer
1. Make sure no Crazradio is connected to the computer
1. Run the https://github.com/bitcraze/crazyflie-lib-python/blob/0.1.7/examples/basiclog.py script.
1. Run the https://github.com/bitcraze/crazyflie-lib-python/blob/0.1.7/examples/basiclog.py script.

Symptoms:

* The script hangs the second time

**Comment by AlexisTM** [comment]
Temporary workaround: Disable the watchdog using the DEBUG flag

**Comment by krichardsson** [comment]
Related to #393

**Comment by evoggy** [comment]
This is closed with the fix for #393.
