### ISSUE TITLE
While charging flight is possible

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#4]
Hi,

I would like to report that in some cases it is possible to (try to) fly while the Crazyflie is charging.

Since the Crazyflie is connected to the charger actual flight is tricky but I don't think it's recommended.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/4
- Originally Reported By: [ ](http://bitbucket.org/the_programmer)
- Originally Created At: 2013-05-11T14:21:19.476

**Comment by krichardsson** [comment]
Flying while charging is useful for chargers where the CF take off from, for instance the Qi charger.
