### ISSUE TITLE
Recommended linking to development environment setup

### ISSUE THREAD

**Issue by peteflorence** [bitcraze/crazyflie-firmware#40]
Hey Bitcraze,

Thanks for the great work on the CrazyFlies.  Wanted to just recommend that on this page: http://wiki.bitcraze.se/projects:crazyflie2:development:ota a prerequisite is added (with a link?) to http://wiki.bitcraze.se/projects:crazyflie:devenv:index#setup_on_ubuntu_1304.  Took me some time to find and so maybe a link might help others.

Also please let me know if there's a better place to provide feedback for the wiki!

Best, Pete

**Comment by tobbeanton** [comment]
Updated wiki page with a comment. It should work on mac and windows with the make environment installed.
