### ISSUE TITLE
build error in usddeck.c (array subscript has type)

### ISSUE THREAD

**Issue by whoenig** [bitcraze/crazyflie-firmware#418]
@whoenig : When repo is cloned as instructed, there is on error respond to make command such as:

src/deck/drivers/src/usddeck.c: In function 'f_gets_without_comments':
src/deck/drivers/src/usddeck.c:238:5: error: array subscript has type 'char' [-Werror=char-subscripts]
     if (isspace(c)) {
     ^
cc1: all warnings being treated as errors
tools/make/targets.mk:26: recipe for target 'usddeck.o' failed
make[1]: *** [usddeck.o] Error 1
Makefile:327: recipe for target 'build' failed
make: *** [build] Error 2

It has nothing about this issue, this is for micro sd deck I guess, since I am not using this deck, by commenting out problematic section, I am able to make the project and fly.

_Originally posted by @tugayalperen in https://github.com/bitcraze/crazyflie-firmware/issues/409#issuecomment-477983043_

**Comment by whoenig** [comment]
@tugayalperen: This was not picked up by the automated build tests. It is related to a PR I recently created. Could you share details about your build environment (which compiler? Do you have any outstanding changes? Any custom configuration in config.mk?).

**Comment by BIsichei** [comment]
@whoenig I'm having this same error when trying to make under the "crazyflie-firmware" directory from the terminal. I cloned the [repo](https://github.com/bitcraze/crazyflie-firmware), initialized and updated submodules, and ran make. As far as I know i don't have any custom configurations. If it helps, i'm running this on laptop running ubuntu 16.04.

**Comment by whoenig** [comment]
Updating your compiler should resolve the issue. I am running locally the following version:

```
$arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q3-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
```

**Comment by tugayalperen** [comment]
I can confirm that, version change solves the problem.

**Comment by BIsichei** [comment]
That fixed it, thanks

**Comment by krichardsson** [comment]
Seems as this is solved? If not please re-open

**Comment by jungr-ait** [comment]
Hi,

I found a simple solution to that issue (https://github.com/USC-ACTLab/crazyflie-firmware/pull/1), just a simple C type cast, which has the nice side effect, that not everyone needs to upgrade the official compiler in Ubunutu 16.04. As @whoenig  said, we could reopen this issue and apply this change, if desired.
