### ISSUE TITLE
HAL

### ISSUE THREAD

**Issue by mkschreder** [bitcraze/crazyflie-firmware#42]
Have you considered using LibK to provide harware abstraction layer? 

https://github.com/mkschreder/martink

There is support for stm32, accelerometers, magnetometers, gyroscopes and many other devices. Also, the library is written to be very lightweight and exposes key functionality through generic interfaces that enforce modular design and high level of code reuse.

**Comment by ataffanel** [comment]
This looks interesting. Right now we are not planing on changing our HAL, but it is interesting to know about the possibilities.
