### ISSUE TITLE
accBiasFound to be renamed to accScaleFound

### ISSUE THREAD

**Issue by AlexisTM** [bitcraze/crazyflie-firmware#425]
Hi, the scale of the accelerometer has been (I think) misnamed to accBiasFound.

https://github.com/bitcraze/crazyflie-firmware/blob/ebf447ee94f524ddf28cccdd7032ff4126f079cc/src/hal/src/sensors_bmi088_bmp388.c#L572-L590

I would rename `accBiasFound` to `accScaleFound` and initialize it after the gyro, next to the other accelerometer scale related variables.

https://github.com/bitcraze/crazyflie-firmware/blob/ebf447ee94f524ddf28cccdd7032ff4126f079cc/src/hal/src/sensors_bmi088_bmp388.c#L117-L126

**Comment by krichardsson** [comment]
I agree, makes sense.

If you issue a pull request, please also update the (unfortunate) copy/paste/similar implementation in  
https://github.com/bitcraze/crazyflie-firmware/blob/ebf447ee94f524ddf28cccdd7032ff4126f079cc/src/hal/src/sensors_bmi088_spi_bmp388.c#L863-L881
