### ISSUE TITLE
No deck init parameter for lighthouse deck

### ISSUE THREAD

**Issue by benkuper** [bitcraze/crazyflie-firmware#439]
After rebuilding the firmware with #define DISABLE_LIGHTHOUSE_DRIVER 0,
the bcLighthouse4 deck doesn't show up in the param list

EDIT : the console callback shows 

SYS: ----------------------------
SYS: Crazyflie 2.1 is up and running!
19.02 +70) MODIFIED
SYS: I am 0x203937434848500E003A003F and I have 1024KB of flash!
CFGBLK: v1, verification [OK]
DECK_CORE: 2 deck(s) found
DECK_CORE: Calling INIT on driver bcLighthouse4 for deck 0
DECK_CORE: Calling INIT on driver bcLedRing for deck 1
IMU: BMI088 Gyro I2C connection [OK].
IMU: BMI088 Accel I2C connection [OK]
IMU: BMP388 I2C connection [OK]
ESTIMATOR: Using Kalman (2) estimator
CONTROLLER: Using PID (1) controller
EEPROM: I2C connection [OK].
STAB: Wait for sensor calibration...
SYS: Free heap: 10176 bytes
LH: Lighthouse bootloader version: 2
STAB: Ready to fly.
LH: Firmware version 1 verified, booting deck!
LH: Synchronized!

so it is recognized in the firmware

![no_lighthouse_deck](https://user-images.githubusercontent.com/1291595/60396154-0ecb6880-9b3e-11e9-8151-8e1598f3f25b.png)

**Comment by ataffanel** [comment]
The console shows that the desk is initialized and you should see the red LED on the deck turning off ~4 seconds after startup which indicates that the deck is running.

Though, the deck init parameter for this deck has not been created yet and it should be.

**Comment by benkuper** [comment]
The red leds turns off indeed after 4 seconds, but isn't it weird that the deck doesn't show up in the list ?

**Comment by ataffanel** [comment]
This list is manually made on the firmware side, as I said this parameter should be added into the lighthouse deck driver. I will add it and close this ticket.
