### ISSUE TITLE
Compilation problem GCC Arm Embedded v8-2018-q4

### ISSUE THREAD

**Issue by victorhook** [bitcraze/crazyflie-firmware#442]
There's a problem when compiling with the new version of the GCC Arm Embedded Toolchain.
When running "make" it throws an error at usb_core.o. 
```
error: 'packed' attribute ignored for type 'uint32_t *' {aka 'long unsigned int *'} [-Werror=attributes]
       USB_OTG_WRITE_REG32( fifo, *((__packed uint32_t *)src) );
       ^~~~~~~~~~~~~~~~~~~
```

To work around it you can run "make" with warning-attributes disabled to bypass it.
```
make EXTRA_CFLAGS=-Wno-attributes
```

**Comment by krichardsson** [comment]
We have upgraded the official compiler version to V8-2019-q3 (updated in the builder image that is used on travis and in the toolbelt) and it seems to work fine.
