### ISSUE TITLE
Add CMSIS-DSP to the firmware project

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#46]
CMSIS-DSP is a dsp (math) lib optimized for cortex-M and distributed under BSD license. We should add it to the build once the cf1-cf2 merge is completed.

**Comment by krichardsson** [comment]
Seems to be done in commit 2f55d075213e1e724e00a0c2b19fb29fb5ea1d81

**Comment by ataffanel** [comment]
Correct, thanks for closing.
