### ISSUE TITLE
Look like copy and waste error in USE_MA_SMOOTHING of flowdeck code

### ISSUE THREAD

**Issue by justinh24** [bitcraze/crazyflie-firmware#475]
Reviewing code I noted the following on line 101 on src/deck/drivers/src/flowdeck_v1_v2.c
      pixelAverages.averageX[pixelAverages.ptr] = (float32_t)accpy;
should probably be:
      pixelAverages.averageY[pixelAverages.ptr] = (float32_t)accpy;

Sorry... My dev environment is not currently set up or I would submit a pull request instead.

**Comment by krichardsson** [comment]
Thanks!
