### ISSUE TITLE
Implement CRTP over USB for Crazyflie 1.0

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-firmware#49]
Currently the Crazyflie 2.0 supports CRTP over USB, but the Crazyflie 1.0 doesn't. Since the CF1 has hardware for USB device and the data-lines are routed to the connector it's possible to implement.

With the merge of the CF1 and CF2 code-base the higher-level functionality for the USB (like CRTP switching radio/USB and USB protocol) could be reused, it's just the lower-level drivers that needs to be duplicated and adapted for the STM32F103 on the CF1 (basically [this](https://github.com/bitcraze/crazyflie-firmware/blob/bigmerge/hal/src/usb_bsp.c) file).

**Comment by ataffanel** [comment]
Unless there is some interest we will not implement this one. So I mark it as wontfix. If anyone is interested feel free to reopen.
