### ISSUE TITLE
Convert ticks in stabilizer loop to sys ticks

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#497]
The tick used in the stabilizer loop is based on a counter that is increased every cycle. The loop runs at 1 kHz and the tick value is passed on to various functions such as estimators and such. The problem is that estimators get measurement data from other sources that are time stamped with the system clock, and the system clock is different from the tick which makes it hard to determine the age of a measurement.

A possible solution would be to use the system clock for the tick in the stabilizer loop instead. Note: Booth stabilizer loop and system clock runs at 1 kHz and it is maybe possible that we could get the same value from the system clock twice in the stabilizer loop if we are unlucky with the timing. Investigate!

**Comment by ataffanel** [comment]
The original implementation was using systick but it was changed in the commit d54d9292a191c.

As far as I can remember the main reason for the change was to be able to reduce the rate of some operation (like the EKF) by doing modulo math on the tick, this can only be done safely if we can guarantee that the tick is the same for the full duration of the loop.

If we continue using these modulo operation for running different operation at different rate, using a loop counter like we do now is likely the best way to achieve it. Though as far as I understand it does not prevent the different algorithm to use the system time as well to asses of the sensor measurement age.
