### ISSUE TITLE
DEBUG_PRINT() doesn't work for long Strings

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#5]
If i put too long Strings in the DEBUG_PRINT() the CF freeze somewhere inside this function (can't see without JTAG).
After Connection with the Client the CF continues, but with bad Printout formatting.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/5
- Originally Reported By: [Sascha Heymann](http://bitbucket.org/sheymann)
- Originally Created At: 2013-05-14T00:25:32.881

**Comment by ataffanel** [comment]
This is fixed: we now have a buffer for the console before connection and we print <F> when the buffer has been full (ie. when we dropped messages)
