### ISSUE TITLE
Revamping memory subsystem

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#500]
Currently the memory subsystem implementation makes hard-link with everything accessed by it. Since we are using it to configure decks like the lighthouse basestation geometry, it adds hard-link from the code of the firmware to the lighthouse deck which is something we want to avoid.

Furthermore, it would be nice to not have a single file poking in all parts of the firmware, so maybe implementing memories as resources that can be registered by other part of the firmware instead of the current fixed list would be a good idea.

This is only about modifying the firmware implementation part of the memory subsystem, the protocol should not need to be modified.

**Comment by jonasdn** [comment]
@krichardsson did this.
