### ISSUE TITLE
FreeRTOS upstream v10.2.1

### ISSUE THREAD

**Issue by pablogs9** [bitcraze/crazyflie-firmware#508]
Is there any plan to update the FreeRTOS kernel version used to a complete and newer version such as v10.2.1 or adding it as third party?

**Comment by krichardsson** [comment]
Hi!

There is no good reason that we are on an old version other than lack of time. We would like to upgrade, and it would be nice to convert it to a sub-repo instead of having it as a part of our code.

If you feel like contributing to the project, pull requests are always welcome :-)

**Comment by pablogs9** [comment]
Please check #510

**Comment by krichardsson** [comment]
Fixed in PR #510

**Comment by krichardsson** [comment]
Lets move it to /vendor
