### ISSUE TITLE
Cross compiling libarm_math

### ISSUE THREAD

**Issue by pablogs9** [bitcraze/crazyflie-firmware#516]
libarm_math is not using crosscompiling prefix, please check #515 
Thanks

**Comment by ataffanel** [comment]
Closed by #515 

Ps. Since in GitHub PR are issues, there is no need to create both an issue and a PR, just the PR would be fine unless there is more to discuss. Thanks for the PRs!

**Comment by pablogs9** [comment]
Sorry, thanks!
