### ISSUE TITLE
Z accuracy problem with Lighthouse and Crazyflie 2.0

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#528]
Instabilities in the Z axis have been observed when using Crazyflie 2.0 and Lighthouse positioning.

This is not expected and could be due to EKF settings of the accelerometers Vs Lighthouse measurement since #461 is pushing Lighghouse angles directly in the EKF.

It needs to be investigated.

**Comment by Yoyasp** [comment]
This also seems to be occuring without the measurments being pushed in the EKF.

**Comment by ataffanel** [comment]
@Yoyasp Can you precise a bit what you have observed? Lighghtouse cannot be used without the EKF, so what you are seeing is likely not related to this bug.

**Comment by Yoyasp** [comment]
I ment that i used the older method of pushing the actual calculated position in the EKF instead of the measured angles.

Today i changed all the parts of the drones and this still happends.

When using a 3d printed prop guard the added weight seems to smooth a lot of it out.

**Comment by krichardsson** [comment]
OK, thanks for the info!
