### ISSUE TITLE
stabilizerAltHoldUpdate() only when AltHolding?

### ISSUE THREAD

**Issue by Hoverbear** [bitcraze/crazyflie-firmware#53]
Hello,
More code review!

I noticed [this](https://github.com/bitcraze/crazyflie-firmware/blob/crazyflie2/modules/src/stabilizer.c#L220-L224)

```c
      // 100HZ
      if (imuHasBarometer() && (++altHoldCounter >= ALTHOLD_UPDATE_RATE_DIVIDER))
      {
        stabilizerAltHoldUpdate();
        altHoldCounter = 0;
      }
```

It seems like this should only be done when `altHold == 1` like [here](https://github.com/bitcraze/crazyflie-firmware/blob/crazyflie2/modules/src/stabilizer.c#L245)? Please let me know if this is incorrect.

**Comment by tobbeanton** [comment]
It is good to have the altHold fusion code running even though it isn't being used at that moment. That is why it is running as soon as there is a barometer present.
