### ISSUE TITLE
Optimize TDoA outlier filter for TDoA2

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#549]
The TDoA outlier filter was written and optimized for TDoA3, but was also added for TDoA2. The sequential nature of TDoA2 has some other requirements and the filter could be modified to work better for TDoA2. One bad packet will generate consecutive outliers that will open up the filter too fast. Setting BUCKET_ACCEPTANCE_LEVEL to 3 or 4 solves the problem, but may be sub optimal for TDoA3. 
We should investigate if the setting works for TDoA3 as well, or if we should add a mechanism to configure the filter based on algorithm.

**Comment by ntamas** [comment]
Just a quick report: we have tested TDoA3 today with the proposed modifications and it seemed okay to us (visually indistinguishable from TDoA2 - no formal measurements though).

**Comment by krichardsson** [comment]
Thanks!
