### ISSUE TITLE
Positioning flowdeck performance

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-firmware#555]
Just a general observation is that I have the impression that positioning with the flowdeck is not working as good as it used to. On an even low textured surface, it is not able to stabilize itself at a height of 50 cm, which it definitely has been able to do before. This might be due to the new lens design, so that we might have to turn down the exposure on the motion sensor, or maybe some changes in the kalmanfilter could have been the issue? Who knows, but we need to investigate this problem.

**Comment by knmcguire** [comment]
Just an update on this one, we are pretty sure that the new lens design is performing worse. There will be an comparison graph soon which will show the motion sensor data at different heights of both flowdecks. More on this soon

**Comment by knmcguire** [comment]
In general it would be great have a more sophisticated standard deviation calculation and send that to the EKF. Current the flow measurement has a fixed STD which is then assuming that each floor  it is flying over is of the same quality. That is ofcourse not the case. 

If the STD can be estimated during flight, flight by flowdeck is probably much more stable.

**Comment by jonasdn** [comment]
This has been solved, somewhat by improvements in firmware, future work will be regarding how to handle losing position data.
