### ISSUE TITLE
Output useful error information when log and param names that are too long

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#588]
See #587 for a background.

Asserts that fail before the watchdog is started are hard to understand for a user since the Crazyflie does not reboot and output assert information to the console. In these cases the Crazyflie turns on the two red LEDs and hangs.

Check if it is possible to start the watchdog earlier in the start up sequence to reduce the number of possible asserts that can be triggered before the watchdog is started.

Specifically make sure log and param init outputs useful error information if names are too long.

**Comment by jonasdn** [comment]
We know have a script `tools/verify/elf_sanity.py` to detect these cases, it is run in CI as well.
