### ISSUE TITLE
Too many variables in a log group cause problems in data transmit

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#6]
If you have more than 5 variables length of a float in a log group this causes the client to tell you that it god something out of TOC

I think the max length for one log packet is reached and it should generate either a second log packet or deny this during compilation

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/6
- Originally Reported By: [Philipp Mohrenweiser](http://bitbucket.org/phiamo)
- Originally Created At: 2013-05-26T14:01:22.550

**Comment by ataffanel** [comment]
Cannot reproduce.
