### ISSUE TITLE
platform specific configuration framework

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-firmware#601]
Add a platform specific structure to have system specific characteristics for arm length, mass etcetera. Now that we have the bolt this might become more necessary. 

Maybe it would be good to add this to some kind of internal memory (is eeprom suitable), or a config file for compiling the code.

These features were mentioned in #559 and #537.

**Comment by jonasdn** [comment]
This will be included in getting Bolt/Bigquad deck out of early access.
