### ISSUE TITLE
Barometer logging does not work with the kalman estimator

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#616]
Sensor reading is not handled the same way for all estimators. When using the kalman estimator the barometer data is not passed on to the logging variable and plotting in the client shows 0.

**How to reproduce:**
1. Switch to the kalman estimator using a parameter or a deck (LPS for instance)
2. Set up logging for baro.pressure in the client

**Expected result:**
The current air pressure, around 1000

**Actual result:**
0

**Comment by whoenig** [comment]
This is related to #722.

**Comment by whoenig** [comment]
This works now with the latest master (tested using CF 2.1 with flow deck installed).
