### ISSUE TITLE
Race condition prevents STM from coming back up when connection is up

### ISSUE THREAD

**Issue by cbiffle** [bitcraze/crazyflie-firmware#63]
Found in b7154ae924505f2d24cca38ee8f9cd231abb03bb.

# Steps to reproduce

1. Power on CrazyFlie (tested with CF2 but applies to both).
2. Connect over Nordic.
3. Reset CrazyFlie STM32 CPU.  Easiest way: use button on debug breakout.

# Expected results

CrazyFlie STM32 comes back up.  Maybe connection drops, worst case.

# Actual results

STM32 hits assert, cannot reestablish connection, must be power-cycled.

# Diagnosis

There's a race condition in queue creation in `radiolinkInit`.  The `syslink` task is started before the queues it uses (particularly `crtpPacketDelivery`) are created.  Since the `syslink` task is higher-priority than the task that creates it (`system`), it immediately preempts.

Normally, no data is available at the nRF UART, and it blocks and returns to sleep before touching the CRTP queues.

However, if the connection is up, the nRF may have a message ready -- in which case `syslink` tries to process it before initialization has completed.

Because the task that does most of the initialization (`system`) is so low-priority, there are probably other bugs of this same shape lurking.

**Comment by tobbeanton** [comment]
Thanks for the fix cbiffle!
