### ISSUE TITLE
Quaternion component naming inconsistency

### ISSUE THREAD

**Issue by simonjwright** [bitcraze/crazyflie-firmware#654]
In `sensfusion6.c` [here](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/sensfusion6.c#L52) and [here](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/sensfusion6.c#L260) the real term of the quaternion is variously named `w` and `q0`.

But in `quaternion_t` in `stabilizer_types.h` [here](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/interface/stabilizer_types.h#L70),  `w` is overlaid on `q3`.

So far as I can tell, the only accesses to `quaternion_t` use `.w`, `.x` etc, so maybe the union with `.q0` etc isn’t needed?

**Comment by krichardsson** [comment]
Yes, that looks a bit ugly and could (should) be cleaned up.

The code in sensorfusion6 is very old while the ```quaternion_t``` was added later, probably when Crazyswarm started to be integrated. I suppose the types were not synchronized at that time.

Unfortunately it looks as if the "q" flavour of ```quaternion_t``` is used in [crtp_commander_generic.c](https://github.com/bitcraze/crazyflie-firmware/blob/8c850fd0cfa3fab81dabbef1b865348eb716a98f/src/modules/src/crtp_commander_generic.c#L336) and [crtp_localization_service.c](https://github.com/bitcraze/crazyflie-firmware/blob/8c850fd0cfa3fab81dabbef1b865348eb716a98f/src/modules/src/crtp_localization_service.c#L194). To make it even worse, I believe the definition of ```quaternion_t``` is doubling as API definition for some CRTP packets.
