### ISSUE TITLE
Fix stabilizer.checkStops variable behavior.

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#674]
Currently, the stabilizer.checkStops log variable indicates if the system is armed or not.

This is redondant with variables already present in system, and looking at the [context](https://github.com/bitcraze/crazyflie-firmware/blob/93cf3d70f807242f23e6f1bacb2f86924746d27c/src/modules/src/stabilizer.c#L297-L302) it seems that this variable was intended to show if the motor are stopped for any reason, not only arming state.

We should figure that out and fix the variable behavior.

**Comment by jonasdn** [comment]
checkStops is removed.
