### ISSUE TITLE
CTRP stack might lose packets

### ISSUE THREAD

**Issue by whoenig** [bitcraze/crazyflie-firmware#681]
The current CRTP stack implementation has several potential places in the firmware, where packets can be lost if an internal queue is full, because return codes are not always checked or blocking calls are not used. This issue is for tracking changes that improve this handling in the STM firmware.

**Comment by ataffanel** [comment]
Thanks for the issue and the PRs! I renamed the title and ticket to reflect that packets are lost in the CRTP stack and not in safelink (safelink only protects the radio packets, and so far it works).

**Comment by jonasdn** [comment]
Is this still an active issue? @ataffanel @whoenig ?

**Comment by whoenig** [comment]
We can close this. The remaining work/bug is captured in #703.
