### ISSUE TITLE
CF2 freezes randomly when I2C code is not in the highest priority task

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie-firmware#69]
As of the 2015.08 release the Crazyflie 2.0 sometimes freezes randomly.

**Comment by krichardsson** [comment]
Warning! If it freezes during flight, the current thrust of the motors will be maintained and the crazyflie will not be possible to control.

**Comment by ataffanel** [comment]
The bug is confirmed to come from the I2C implementation. Reverted a commit that affected the tasks priorities and made this bug apparent.

We still need to fix the underlying I2C implementation.
