### ISSUE TITLE
Questions about log parameters

### ISSUE THREAD

**Issue by 864419409** [bitcraze/crazyflie-firmware#690]
Hello, I recently studied how to record parameters by daily logging, but I was not quite sure about the physical meaning of some parameters in the process of choosing parameters.I inquired the forum and many places all did not find the complete explanation document, would like to ask, where should I inquire their physical meaning?The following figure shows some of the parameters that might be used.
Thank you for your answer.
![4d7a182983aada3260186def3d895c3](https://user-images.githubusercontent.com/70308308/107154132-3508e980-69ac-11eb-9e26-00a739a3280c.png)

**Comment by krichardsson** [comment]
Unfortunately there is currently no documentation for the log variables, the best place for information is the source code. You can find them by searching the code base for "LOG_GROUP_START" which will tell you where the log groups are defined. In those group blocks you can find the individual log variables, mainly defined using the "LOG_ADD" macro. The second argument of the LOG_ADD macro is the name and the last argument is the actual C-variable that is logged. You can search for where this variable is used to figure out what it means.

**Comment by 864419409** [comment]
Thank you for your reply. I will try your method right away. If it is convenient, could you please tell me where to extract the source code of this piece?


On 2/8/2021 19:15，Kristoffer Richardsson<notifications@github.com> wrote：

Unfortunately there is currently no documentation for the log variables, the best place for information is the source code. You can find them by searching the code base for "LOG_GROUP_START" which will tell you where the log groups are defined. In those group blocks you can find the individual log variables, mainly defined using the "LOG_ADD" macro. The second argument of the LOG_ADD macro is the name and the last argument is the actual C-variable that is logged. You can search for where this variable is used to figure out what it means.

**Comment by krichardsson** [comment]
Hi! 

Can we close this issue?

**Comment by 864419409** [comment]
yes of course，  Sorry, I'm still learning how to use the website


On 3/2/2021 00:01，Kristoffer Richardsson<notifications@github.com> wrote：

Hi!

Can we close this issue?
