### ISSUE TITLE
Instability when dropping or switching from full positive roll/pitch to full negative

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#7]
When dropping quickly in altitude or when switching from going full positive roll/pitch to full negative roll/pitch (or vise verse) the Crazyflie will become very unstable and wobbles.

This has been noted in the forums: http://forum.bitcraze.se/viewtopic.php?f=11&t=264

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/7
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-06-03T14:08:20.619

**Comment by ataffanel** [comment]
This was fixed by tweaking the PID settings and, on Crazyflie 2.0, by having more powerful motors.
