### ISSUE TITLE
Magetometer

### ISSUE THREAD

**Issue by Sigmund-SJTUer** [bitcraze/crazyflie-firmware#701]
Excuse me, is the magetometer very important for Crazyflie? And what effect does turning off the magnetometer have on the Crazyflie?  How to turn off the magetometer?  Thanks.

**Comment by ataffanel** [comment]
The magnetometer was not found to be very useful on Crazyflie 2.0 so it has been removed in Crazyflie 2.1.

In Crazyflie 2.0 the magnetometer is not used by default so it is as if it was off. I am not sure how to turn off the magnetometer chip itself, but doing so would have no practical effect on the Crazyflie.

**Comment by Sigmund-SJTUer** [comment]
Thank you, sir
