### ISSUE TITLE
uSD Deck: Add event logging support

### ISSUE THREAD

**Issue by whoenig** [bitcraze/crazyflie-firmware#704]
The current usd deck driver supports logging to uSD card at a fixed frequency. However, this does not allow to log asynchronous events, such as ones that occur when a new sensor measurement is available. Ideally, we support both event logging and regular fixed-frequency logging.

# Proposed API 

## Event System

Similar to params, logs, and decks, a module can define an event datatype:

New data structure:
```
typedef struct eventtype_s {
  char* name;
} eventType;

```
new macro:
`EVENT()`

A module can then call the following function to trigger a new event:

```
eventTrigger(const eventType*)
```
## uSD Logging Backend

The uSD driver will be the first driver that can react to events. Users will be able to configure which variable to log at either a fixed frequency, or when an event occurred.

# Proposed File Format

### Current File Format

```
500   # frequency
100    # buffer size
log   # file name
1     # enable on startup (0/1)
2     # mode (0: disabled, 1: synchronous stabilizer, 2: asynchronous)
<list of variables (one per line)>
```

### Proposed File Format

```
1 # version
100 # buffer size in bytes
log # file name
1     # enable on startup (0/1)
on:fixedFrequency
500   # frequency
2     # mode (0: disabled, 1: synchronous stabilizer, 2: asynchronous)
<list of variables (one per line)>
on:eventName1
<list of variables (one per line)>
on:eventName2
<list of variables (one per line)>
```
### Current File Format

```
uint8_t  num_log_variables
varname1(vartype1),varname2(vartype2),...,varnameN(vartypeN),
<CRC>
uint8_t sets_to_write; binary data for all sets; <CRC>
```

### Proposed File Format

The new, proposed file format generalizes this concept by adding an event type to each dataset and the beginning of the header can list variable names and types for each event type:

```
uint8_t 0xBC header
uint16_t version
uint16_t num_event_types
for each event type:
   uint16_t event_id
   eventName (null-terminated)
   uint16_t num_variables
   varname1(vartype1),varname2(vartype2),...,varnameN(vartypeN),
for each event:
   uint16_t event_id
   uint32_t timestamp (usec timer)
   data (length defined by TOC event type)
```

# Notes

* This will be a breaking change in terms of file format. However, the new file format is finally versioned, and both decoding scripts and usddeck driver are in the same repository, so this should be OK. Adding the magic 0xBC header at the top, should allow us to detect the new format with high probability.
* There is currently no CRC in this design; an invalid record can be easily detected by looking at the file length. This is because I've never observed a CRC check failure. Alternatively, we can also CRC over larger chunks or over the whole file.
* We should avoid closing/opening the file frequently, as we currently do, as this creates most of the SPI traffic. This likely means that we are less resilient to firmware crashes compared to before. However, debugging a firmware crash does not seem to be a good use case of the uSD card deck in the first place?

**Comment by krichardsson** [comment]
Ping @Williamwenda

**Comment by tobbeanton** [comment]
I think this is a great start.

**Comment by whoenig** [comment]
This has been merged.
