### ISSUE TITLE
Crazyflie 2.0 crashes when connected with USB

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-firmware#72]
When connected with USB the watchdog kicks-in and restarts the Crazyflie 2.0.

**Comment by ataffanel** [comment]
The fix triggers communication errors and should be reverted

**Comment by krichardsson** [comment]
The temporary fix in 51e565d6388bd503c20e3069540e11e189ca4328 seems to have been reverted in ef83b9268d3726a096d29d4828a9bdf0931d936f. Assume that the real problem is fixed, closing.
