### ISSUE TITLE
Flight Control

### ISSUE THREAD

**Issue by Sigmund-SJTUer** [bitcraze/crazyflie-firmware#740]
I wanna control Crazyflie2.1 without flowdeck and multiranger. But MotionCommander lib is designed on basis of these two modules. How should I do?

**Comment by knmcguire** [comment]
Hi! This is difficult to do autonomously since you need a positioning system for this. Please checkout our forum.bitcraze.io if anybody tried this before.

Best regards,

Kimberly

**Comment by Sigmund-SJTUer** [comment]
We have a optical capture positioning system called VICON. I wanna use the feedback data of this system to control crazyflie2.1. Is there some examples to be referred?

**Comment by whoenig** [comment]
The Crazyswarm has integrated VICON support: https://crazyswarm.readthedocs.io/. Another option is to use the python-lib and the VICON DataStream SDK.

**Comment by Sigmund-SJTUer** [comment]
Thanks.
