### ISSUE TITLE
Cx-freeze error trying to build dev version on windows

### ISSUE THREAD

**Issue by Spordoz** [bitcraze/crazyflie-firmware#779]
Generating code
    Finished generating code
    running build_scripts
    creating build\scripts-3.9
    copying and adjusting cxfreeze -> build\scripts-3.9
    copying and adjusting cxfreeze-quickstart -> build\scripts-3.9
    error: file 'C:\Users\User\AppData\Local\Temp\pip-install-wry98gu3\cx-freeze_0701f85242b646a8a796f458075630ab\cxfreeze-postinstall' does not exist

In setup.py line 79: 
`if sys.platform == 'win32':
    platform_dev_requires.extend(['cx_freeze==5.1.1', 'jinja2==2.10.3'])`

change this to:
`if sys.platform == 'win32':
    platform_dev_requires.extend(['cx_freeze==6.6', 'jinja2==2.10.3'])`

This fixed it for me.

Im gonna assume that 5.1.1 is missing said required file, i have not checked this however.

**Comment by knmcguire** [comment]
Very sorry for the late reply but this issue seemed to have fallen through the cracks. I will close this because this seems to be related to the CMSIS submodule, which should be mentioned in [their repository](https://github.com/ARM-software/CMSIS_5/)
