### ISSUE TITLE
SD logging - assert fail if filename is longer than 10 chars

### ISSUE THREAD

**Issue by wydmynd** [bitcraze/crazyflie-firmware#797]
as defined in config.txt
don't have the assert information but easy to replicate

**Comment by krichardsson** [comment]
Thanks for the report! 
Sounds plausible that this has not been tested...

**Comment by jonasdn** [comment]
I can't actually seem to reproduce this, when exactly does it assert?

**Comment by wydmynd** [comment]
I'm sorry its been a while , if you can't reproduce it , you can close the issue and I will try to reproduce , and reopen with more info  if I succeed
