### ISSUE TITLE
usd unable to log

### ISSUE THREAD

**Issue by easy98** [bitcraze/crazyflie-firmware#798]
Hi,

My usd is not able to log any logging variables due to the assert problem here(https://github.com/bitcraze/crazyflie-firmware/blob/b448553725634aa83d25b356a7de12ba61647377/src/deck/drivers/src/usddeck.c#L504). I use the latest firmware.

> SUMMARY
========

PARAMETERS
 * /crazyflieTypes/CF21SingleMarker/batteryVoltageWarning: 3.8
 * /crazyflieTypes/CF21SingleMarker/batteryVoltateCritical: 3.7
 * /crazyflieTypes/CF21SingleMarker/bigQuad: False
 * /crazyflieTypes/CF21SingleMarker/dynamicsConfiguration: 0
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/i_range_z: 0.4
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kR_xy: 70000
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kR_z: 60000
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kd_omega_rp: 200
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kd_xy: 0.2
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kd_z: 0.4
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/ki_xy: 0.05
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/ki_z: 0.05
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kp_xy: 0.4
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kp_z: 1.25
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kw_xy: 20000
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/kw_z: 12000
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/mass: 0.032
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/ctrlMel/massThrust: 132000
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/kalman/mNGyro_rollpitch: 0.1
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/kalman/mNGyro_yaw: 0.1
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/kalman/pNAcc_xy: 1.0
 * /crazyflieTypes/CF21SingleMarker/firmwareParams/kalman/pNAcc_z: 2.0
 * /crazyflieTypes/CF21SingleMarker/markerConfiguration: 3
 * /crazyflieTypes/default/batteryVoltageWarning: 3.8
 * /crazyflieTypes/default/batteryVoltateCritical: 3.7
 * /crazyflieTypes/default/bigQuad: False
 * /crazyflieTypes/default/dynamicsConfiguration: 0
 * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_z: 0.4
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kR_xy: 70000
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kR_z: 60000
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_omega_rp: 200
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_xy: 0.2
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_z: 0.4
 * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_xy: 0.05
 * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_z: 0.05
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kp_xy: 0.4
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kp_z: 1.25
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kw_xy: 20000
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kw_z: 12000
 * /crazyflieTypes/default/firmwareParams/ctrlMel/mass: 0.032
 * /crazyflieTypes/default/firmwareParams/ctrlMel/massThrust: 132000
 * /crazyflieTypes/default/markerConfiguration: 0
 * /crazyflieTypes/defaultSingleMarker/batteryVoltageWarning: 3.8
 * /crazyflieTypes/defaultSingleMarker/batteryVoltateCritical: 3.7
 * /crazyflieTypes/defaultSingleMarker/bigQuad: False
 * /crazyflieTypes/defaultSingleMarker/dynamicsConfiguration: 0
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/i_range_z: 0.4
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kR_xy: 70000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kR_z: 60000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kd_omega_rp: 200
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kd_xy: 0.2
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kd_z: 0.4
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/ki_xy: 0.05
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/ki_z: 0.05
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kp_xy: 0.4
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kp_z: 1.25
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kw_xy: 20000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kw_z: 12000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/mass: 0.032
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/massThrust: 132000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/kalman/mNGyro_rollpitch: 0.2
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/kalman/mNGyro_yaw: 0.1
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/kalman/pNAcc_xy: 4.0
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/kalman/pNAcc_z: 8.0
 * /crazyflieTypes/defaultSingleMarker/markerConfiguration: 3
 * /crazyflieTypes/large/batteryVoltageWarning: 11.4
 * /crazyflieTypes/large/batteryVoltateCritical: 11.1
 * /crazyflieTypes/large/bigQuad: True
 * /crazyflieTypes/large/dynamicsConfiguration: 0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_z: 4.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kR_xy: 30000
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kR_z: 40000
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_omega_rp: 100
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_xy: 3.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_z: 3.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_xy: 1.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_z: 2.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kp_xy: 8.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kp_z: 8.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kw_xy: 9000
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kw_z: 10000
 * /crazyflieTypes/large/firmwareParams/ctrlMel/mass: 0.38
 * /crazyflieTypes/large/firmwareParams/ctrlMel/massThrust: 5400
 * /crazyflieTypes/large/markerConfiguration: 2
 * /crazyflieTypes/medium/batteryVoltageWarning: 7.6
 * /crazyflieTypes/medium/batteryVoltateCritical: 7.4
 * /crazyflieTypes/medium/bigQuad: True
 * /crazyflieTypes/medium/dynamicsConfiguration: 0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_z: 2.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kR_xy: 50000
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kR_z: 60000
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_omega_rp: 200
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_xy: 1.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_z: 1.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_xy: 0.1
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_z: 0.5
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kp_xy: 2.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kp_z: 3
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kw_xy: 16000
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kw_z: 12000
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/mass: 0.11
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/massThrust: 23000
 * /crazyflieTypes/medium/markerConfiguration: 1
 * /crazyflies: [{'initialPositio...
 * /crazyswarm_server/enable_logging: True
 * /crazyswarm_server/enable_parameters: True
 * /crazyswarm_server/firmwareParams/commander/enHighLevel: 1
 * /crazyswarm_server/firmwareParams/kalman/resetEstimation: 1
 * /crazyswarm_server/firmwareParams/locSrv/extPosStdDev: 1e-3
 * /crazyswarm_server/firmwareParams/locSrv/extQuatStdDev: 0.05
 * /crazyswarm_server/firmwareParams/ring/effect: 16
 * /crazyswarm_server/firmwareParams/ring/headlightEnable: 0
 * /crazyswarm_server/firmwareParams/ring/solidBlue: 2
 * /crazyswarm_server/firmwareParams/ring/solidGreen: 0
 * /crazyswarm_server/firmwareParams/ring/solidRed: 0
 * /crazyswarm_server/firmwareParams/stabilizer/controller: 2
 * /crazyswarm_server/firmwareParams/stabilizer/estimator: 2
 * /crazyswarm_server/force_no_cache: False
 * /crazyswarm_server/genericLogTopicFrequencies: [50, 50, 50, 50]
 * /crazyswarm_server/genericLogTopic_log1_Variables: ['stateEstimate.x...
 * /crazyswarm_server/genericLogTopic_log2_Variables: ['ranging.distanc...
 * /crazyswarm_server/genericLogTopic_log3_Variables: ['ranging.distanc...
 * /crazyswarm_server/genericLogTopic_log4_Variables: ['acc.x', 'acc.y'...
 * /crazyswarm_server/genericLogTopics: ['log1', 'log2', ...
 * /crazyswarm_server/motion_capture_type: none
 * /crazyswarm_server/object_tracking_type: motionCapture
 * /crazyswarm_server/print_latency: False
 * /crazyswarm_server/save_point_clouds: ~/pointCloud.ot
 * /crazyswarm_server/send_position_only: False
 * /crazyswarm_server/vicon_host_name: 192.168.1.100
 * /crazyswarm_server/world_frame: bitcraze
 * /crazyswarm_server/write_csvs: False
 * /crazyswarm_teleop/csv_file: /home/coven-lab/c...
 * /crazyswarm_teleop/timescale: 0.8
 * /dynamicsConfigurations/0/maxFitnessScore: 0.001
 * /dynamicsConfigurations/0/maxPitch: 1.4
 * /dynamicsConfigurations/0/maxPitchRate: 20.0
 * /dynamicsConfigurations/0/maxRoll: 1.4
 * /dynamicsConfigurations/0/maxRollRate: 20.0
 * /dynamicsConfigurations/0/maxXVelocity: 2.0
 * /dynamicsConfigurations/0/maxYVelocity: 2.0
 * /dynamicsConfigurations/0/maxYawRate: 10.0
 * /dynamicsConfigurations/0/maxZVelocity: 3.0
 * /joy/dev: /dev/input/js0
 * /markerConfigurations/0/numPoints: 4
 * /markerConfigurations/0/offset: [0.0, -0.01, -0.04]
 * /markerConfigurations/0/points/0: [0.0177184, 0.013...
 * /markerConfigurations/0/points/1: [-0.0262914, 0.05...
 * /markerConfigurations/0/points/2: [-0.0328889, -0.0...
 * /markerConfigurations/0/points/3: [0.0431307, -0.03...
 * /markerConfigurations/1/numPoints: 4
 * /markerConfigurations/1/offset: [0.0, 0.0, -0.03]
 * /markerConfigurations/1/points/0: [-0.00896228, -0....
 * /markerConfigurations/1/points/1: [-0.0156318, 0.09...
 * /markerConfigurations/1/points/2: [0.0461693, -0.08...
 * /markerConfigurations/1/points/3: [-0.0789959, -0.0...
 * /markerConfigurations/2/numPoints: 4
 * /markerConfigurations/2/offset: [0.0, 0.0, -0.06]
 * /markerConfigurations/2/points/0: [0.0558163, -0.00...
 * /markerConfigurations/2/points/1: [-0.0113941, 0.00...
 * /markerConfigurations/2/points/2: [-0.0306277, 0.05...
 * /markerConfigurations/2/points/3: [0.0535816, -0.04...
 * /markerConfigurations/3/numPoints: 1
 * /markerConfigurations/3/offset: [0.0, -0.01, -0.04]
 * /markerConfigurations/3/points/0: [0.0177184, 0.013...
 * /numDynamicsConfigurations: 1
 * /numMarkerConfigurations: 4
 * /rosdistro: melodic
 * /rosversion: 1.14.9
 * /vicon/datastream_hostport: 192.168.1.100:801
 * /vicon/stream_mode: ClientPull
 * /vicon/tf_ref_frame_id: /world

NODES
  /
    crazyswarm_server (crazyswarm/crazyswarm_server)
    crazyswarm_teleop (crazyswarm/crazyswarm_teleop)
    joy (joy/joy_node)
    rviz (rviz/rviz)
    vicon (vicon_bridge/vicon_bridge)

auto-starting new master
process[master]: started with pid [29715]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 887091b2-d221-11eb-9720-606dc7c60f33
process[rosout-1]: started with pid [29726]
started core service [/rosout]
process[crazyswarm_server-2]: started with pid [29733]
process[joy-3]: started with pid [29734]
process[crazyswarm_teleop-4]: started with pid [29735]
process[vicon-5]: started with pid [29741]
[ INFO] [1624232703.525606116]: Wait for services...
[ INFO] [1624232703.526491251]: waitForService: Service [/emergency] has not been advertised, waiting...
process[rviz-6]: started with pid [29747]
[ INFO] [1624232703.540027279]: Connecting to Vicon DataStream SDK at 192.168.1.100:801 ...
[ INFO] [1624232703.567869179]: waitForService: Service [/emergency] is now available.
[ INFO] [1624232703.569099076]: Manager ready.
ch: 1
[ INFO] [1624232703.591669117]: Adding CF: cf4 (radio://0/100/2M/E7E7E7E704, cf4)...
[ INFO] [1624232703.608835600]: CF ctor: 0.016464 s
[ INFO] [1624232703.613486238]: [cf4] SYS: ----------------------------
[ INFO] [1624232703.615937065]: [cf4] SYS: Crazyflie 2.1 is up and running!
[ INFO] [1624232703.618592807]: [cf4] SYS: Build 215:a7e0aae54b23 (2021.03 +215) CLEAN
[ INFO] [1624232703.622327383]: [cf4] SYS: I am 0x20373357594B5007003D0031 and I have 1024KB of flash!
[ INFO] [1624232703.623845705]: [cf4] CFGBLK: v1, verification [OK]
[ INFO] [1624232703.625293548]: [cf4] DECK_CORE: 1 deck(s) found
[ INFO] [1624232703.627983158]: [cf4] DECK_CORE: Calling INIT on driver bcUSD for deck 0
[ INFO] [1624232703.629399868]: [cf4] uSD: mount SD-Card [OK].
[ INFO] [1624232703.631729548]: [cf4] IMU: BMI088: Using I2C interface.
[ INFO] [1624232703.633055356]: [cf4] uSD: wait for sensors
[ INFO] [1624232703.635358707]: [cf4] IMU: BMI088 Gyro connection [OK].
[ INFO] [1624232703.637629506]: [cf4] IMU: BMI088 Accel connection [OK]
[ INFO] [1624232703.640318290]: [cf4] IMU: BMP388 I2C connection [OK]
[ INFO] [1624232703.642978629]: [cf4] ESTIMATOR: Using Complementary (1) estimator
[ INFO] [1624232703.645352116]: [cf4] CONTROLLER: Using PID (1) controller
[ INFO] [1624232703.647711081]: [cf4] MTR-DRV: Using brushed motor driver
[ INFO] [1624232703.650089538]: [cf4] SYS: About to run tests in system.c.
[ INFO] [1624232703.651573230]: [cf4] EEPROM: I2C connection [OK].
[ INFO] [1624232703.653032914]: [cf4] STORAGE: Storage check [OK].
[ INFO] [1624232703.655360071]: [cf4] IMU: BMI088 gyro self-test [OK]
[ INFO] [1624232703.656920159]: [cf4] DECK_CORE: Deck 0 test [OK].
[ INFO] [1624232703.659747646]: [cf4] SYS: The system resumed after a failed assert [WARNING]
[ INFO] [1624232703.662697624]: [cf4] SYS: Assert failed at .//src/deck/drivers/src/usddeck.c:504
[ INFO] [1624232703.664975686]: [cf4] SYS: cfAssertNormalStart [FAIL]
[ INFO] [1624232703.665778170]: [cf4] Requesting parameters...
[ INFO] [1624232703.694510701]: Found variables in cache.
[ WARN] [1624232703.706540260]: Couldn't set gain on joystick force feedback: Bad file descriptor
[ INFO] [1624232703.707388153]: Opened joystick: /dev/input/js0. deadzone_: 0.050000.
[ INFO] [1624232704.013898737]: [cf4] reqParamTOC: 0.405002 s (225 params)
[ INFO] [1624232704.013936989]: [cf4] Requesting logging variables...
[ INFO] [1624232704.016709976]: Found variables in cache.
[ INFO] [1624232704.017238701]: [cf4] reqLogTOC: 0.003365 s
[ INFO] [1624232704.043680589]: [cf4] logBlocks: 0.405002 s
[ INFO] [1624232704.043718211]: Requesting memories...
[ WARN] [1624232704.170863217]: [cf4] Link Quality low (0.480000)
[ INFO] [1624232704.249291565]: [cf4] SYS: ----------------------------
[ INFO] [1624232704.273877261]: [cf4] SYS: Crazyflie 2.1 is up and running!
[ WARN] [1624232704.274000973]: [cf4] Link Quality low (0.070000)
[ INFO] [1624232704.276953192]: [cf4] SYS: Build 215:a7e0aae54b23 (2021.03 +215) CLEAN
[ INFO] [1624232704.298269926]: [cf4] ash!
[ INFO] [1624232704.299945872]: [cf4] CFGBLK: v1, verification [OK]
[ INFO] [1624232704.323444830]: [cf4] DECK_CORE: 1 deck(s) found
[ INFO] [1624232704.326513214]: [cf4] DECK_CORE: Calling INIT on driver bcUSD for deck 0
[ INFO] [1624232704.336100563]: [cf4] uSD: mount SD-Card [OK].
[ INFO] [1624232704.338625314]: [cf4] IMU: BMI088: Using I2C interface.
[ INFO] [1624232704.340154824]: [cf4] uSD: wait for sensors
[ WARN] [1624232704.372271294]: [cf4] Link Quality low (0.630000)
[ INFO] [1624232705.337373600]: [cf4] IMU: BMI088 Gyro connection [OK].
[ INFO] [1624232705.391946324]: [cf4] IMU: BMI088 Accel connection [OK]
[ INFO] [1624232705.405754023]: [cf4] IMU: BMP388 I2C connection [OK]
[ INFO] [1624232705.426961765]: [cf4] ESTIMATOR: Using Complementary (1) estimator
[ INFO] [1624232705.429507587]: [cf4] CONTROLLER: Using PID (1) controller
[ INFO] [1624232705.431969630]: [cf4] MTR-DRV: Using brushed motor driver
[ INFO] [1624232705.434565329]: [cf4] SYS: About to run tests in system.c.
[ WARN] [1624232705.627962767]: [cf4] Link Quality low (0.030000)
[ INFO] [1624232705.635151848]: [cf4] SYS: ----------------------------
[ INFO] [1624232705.660259452]: [cf4] SYS: Crazyflie 2.1 is up and running!
[ INFO] [1624232705.663078305]: [cf4] SYS: Build 215:a7e0aae54b23 (2021.03 +215) CLEAN
[ INFO] [1624232705.684592779]: [cf4] ash!
[ INFO] [1624232705.686133906]: [cf4] CFGBLK: v1, verification [OK]
[ INFO] [1624232705.709374056]: [cf4] DECK_CORE: 1 deck(s) found
[ INFO] [1624232705.712371165]: [cf4] DECK_CORE: Calling INIT on driver bcUSD for deck 0
[ INFO] [1624232705.721803673]: [cf4] uSD: mount SD-Card [OK].
[ INFO] [1624232705.724346298]: [cf4] IMU: BMI088: Using I2C interface.
[ INFO] [1624232705.725845507]: [cf4] uSD: wait for sensors
[ WARN] [1624232705.729431289]: [cf4] Link Quality low (0.330000)
terminate called after throwing an instance of 'std::runtime_error'
  what():  timeout
[crazyswarm_server-2] process has died [pid 29733, exit code -6, cmd /home/coven-lab/crazyswarm/ros_ws/devel/lib/crazyswarm/crazyswarm_server __name:=crazyswarm_server __log:=/home/coven-lab/.ros/log/887091b2-d221-11eb-9720-606dc7c60f33/crazyswarm_server-2.log].
log file: /home/coven-lab/.ros/log/887091b2-d221-11eb-9720-606dc7c60f33/crazyswarm_server-2*.log

**Comment by krichardsson** [comment]
Since you are using the 2021.03 release, the assert is actually here https://github.com/bitcraze/crazyflie-firmware/blob/2021.03/src/deck/drivers/src/usddeck.c#L504

**Comment by krichardsson** [comment]
It seems to be related to the CORE log implementation we did lately. Also see #791

**Comment by jonasdn** [comment]
Hi!

Could you perhaps share your log configuration? What variables are you trying to log?

**Comment by easy98** [comment]
Hi,

It's my configuration file:

> 1     # version
> 512   # buffer size in bytes
> log   # file name
> 1     # enable on startup (0/1)
> on:fixedFrequency
> 250     # frequency
> 1     # mode (0: disabled, 1: synchronous stabilizer, 2: asynchronous)
> 
> acc.x
> acc.y
> acc.z
> gyro.x
> gyro.y
> gyro.z
> baro.asl
> baro.temp
> baro.pressure
> stabilizer.roll
> stabilizer.pitch
> stabilizer.yaw
> stabilizer.thrust
> ctrltarget.roll
> ctrltarget.pitch
> ctrltarget.yaw

**Comment by jonasdn** [comment]
I think the latest PR (#800) should fix this, are you able to test it @easy98 ?

**Comment by easy98** [comment]
Thank you for your reply!

I change the PR. Now it can create a log file but it's empty and unable to log anything.

**Comment by easy98** [comment]
@jonasdn Hi, I update the PR and do some tests. Now the config file can be read  and a log file can be created in the sd-card. But it's totally empty. I am so confused about it and don't know what might be the problem. Do you have any suggestions? Thanks!

**Comment by sstroobants** [comment]
Hi, has this ever been resolved? I think I have the same issues. As soon as I set the usd.logging parameter in the cfclient to 0, it writes the data to file.

**Comment by krichardsson** [comment]
@sstroobants Please open a new issue if you think you have found a bug or start a discussion (in http://discussions.bitcraze.io/) if you need support. Also refer to this issue if you think there is a relation.
