### ISSUE TITLE
Crazyflie Bolt: pm.state always reports that the drone is on charger

### ISSUE THREAD

**Issue by ntamas** [bitcraze/crazyflie-firmware#819]
It looks like the current firmware erroneously reports that the drone is on charger (even if it isn't) when using it on a Crazyflie Bolt. The `pm.state` variable is equal to 2 when no USB cable is connected and the drone is sitting idle on the desk with a charged battery. On a stock Crazyflie, `pm.state` is equal to 0 in this case. As a consequence, `system.canFly` is zero and the Crazyflie Python client disables the command-based flight mode buttons.

**Comment by ntamas** [comment]
Further investigation shows that this happens only with the 1-cell Li-ion prototype (as outlined in [this blog post](https://www.bitcraze.io/2020/10/testing-crazyflie-bolt-and-1-cell-li-ion/) ) but not with a similar build that has a two-cell Li-Po battery.

**Comment by knmcguire** [comment]
hi! this is probably a topic for @tobbeanton but he is still on a holiday for another week. I'll assign him so that he can investigate once he is back

**Comment by tobbeanton** [comment]
Issue confirmed! The problem most likely lies in the nRF part of the power management code. I will investigate further.

**Comment by tobbeanton** [comment]
[nRF issue ](https://github.com/bitcraze/crazyflie2-nrf-firmware/issues/61) solved by setting flags to 0 if charger is not present.
