### ISSUE TITLE
Cavemod firmware

### ISSUE THREAD

**Issue by SaraS00** [bitcraze/crazyflie-firmware#836]
Hello, I tried to use the tunnel_tests.py code from the cavemod firmware ( MadeInPierre /
crazyflie-firmware ) in order to get the RSSI. However I found that the RSSI is always equal to 0 in the ping_log.txt file where the data was saved after the execution, and sometimes the M4 red LED is fully lit and the M1 orange LED is also fully lit for the connected Crazyflie. It stops sending logs and requires to restart it. I don't know the reason of this issue. One more point is that when we place some Crazyflies far from the Crazyradio and the other ones closer to it the connected Crazyflie does't respond which means that the relay protocol doesn't work correctly (it may be because the RSSI value takes always 0 ?). Is there a way to fix those issues ?

**Comment by knmcguire** [comment]
Hi! sorry for the late reply

 This seems quite specific to that repository. Perhaps you should make an issue in their repository instead?
