### ISSUE TITLE
AI-deck reset after system start

### ISSUE THREAD

**Issue by gemenerik** [bitcraze/crazyflie-firmware#880]
In Gap8Task, the reset (GPIO4) is pulled after systemWaitStart()+1s. This interferes with any app using UART1 to communicate with the AI-deck.

**Comment by jonasdn** [comment]
We should not reset the deck after `systemWaitStart()` without a very very very good reason.

**Comment by jonasdn** [comment]
This will be fixed as part of getting the AI deck out of early access.
