### ISSUE TITLE
Spin loops in uart send functions 

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-firmware#883]
The `uart1SendData()` and `uart2SendData()` functions uses a spin loop to determine when the next byte can be pushed to the UART. Sending too much data continuously using these functions will block the task and is likely to cause starvation problems in the system. 

Note: `uart1Putchar()` and `uart2Putchar()` are calling the send data functions and have the same problem

The suggested solution is to replace the spin loop  with an interrupt and semaphore.

**Comment by knmcguire** [comment]
fixed by https://github.com/bitcraze/crazyflie-firmware/pull/1068
