### ISSUE TITLE
Add ability to reconnect when using Esky transmitter

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-firmware#9]
The crazyflie AND the Esky transmitter has to be restarted to reconnect.

With this improvement the crazyflie should go into listen mode if there is no connection. Then only the Esky transmitter has to be restarted. 

Important if CF is lost. Also to get a healthier ON/OFF - button.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/9
- Originally Reported By: [Mathias ](http://bitbucket.org/Surrender)
- Originally Created At: 2013-06-26T22:06:34.952

**Comment by krichardsson** [comment]
Will not implement eSky support in CF2
