### ISSUE TITLE
Micro SD card log files are empty when logging LPS data

### ISSUE THREAD

**Issue by rtkartista** [bitcraze/crazyflie-firmware#932]
The output on the cfcilent's CONSOLE
`---
SYS: Crazyflie 2.0 is up and running!
SYS: Build 8:ca6c5b39e85a (2022.01-rc1 +8) MODIFIED
SYS: I am 0x2035355237485007001E0038 and I have 1024KB of flash!
CFGBLK: v1, verification [OK]
DECK_CORE: 2 deck(s) found
DECK_CORE: Calling INIT on driver bcUSD for deck 0
uSD: mount SD-Card [OK].
DECK_CORE: Calling INIT on driver bcDWM1000 for deck 1
uSD: wait for sensors
MPU9250 I2C connection [OK].
AK8963 I2C connection [OK].
LPS25H I2C connection [OK].
ESTIMATOR: Using Kalman (2) estimator
CONTROLLER: Using PID (1) controller
MTR-DRV: Using brushed motor driver
PLATFORM: Low interference mode. NRF51 TX power offset by -12db.
SYS: About to run tests in system.c.
EEPROM: I2C connection [OK].
STORAGE: Storage check [OK].
AK8963: Self test [OK].
DECK_CORE: Deck 0 test [OK].
DECK_CORE: Deck 1 test [OK].
SYS: Self test passed!
STAB: Wait for sensor calibration...
SYS: Free heap: 16040 bytes
DWM: Automatic mode: detected TDoA2
STAB: Ready to fly.
![Screenshot from 2022-02-02 17-42-35](https://user-images.githubusercontent.com/62306070/152267304-4ae3c132-ab94-4cf0-a591-c8eba8c07dc0.png)
uSD: Config read [OK].
uSD: malloc buffer 600 bytes uSD: [OK].
uSD: Logging to: log07
STAB: WARNING: stabilizer loop rate is off (909)`

Below is the config file
`
1     # version
700   # buffer size in bytes
log   # file name
1     # enable on startup (0/1)
on:fixedFrequency
500     # frequency
1     # mode (0: disabled, 1: synchronous stabilizer, 2: asynchronous)
tdoa2.d7-0
tdoa2.d0-1
tdoa2.d1-2
tdoa2.d2-3
tdoa2.d3-4
tdoa2.d4-5
tdoa2.d5-6
tdoa2.d6-7
on:activeMarkerModeChanged
`

**Comment by knmcguire** [comment]
@rtkartista I see you closed this issue again. Was your problem resolved in the end? What did you change to resolve the issue?
